// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/iracing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOAuthClient creates a new instance of MockOAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthClient {
	mock := &MockOAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOAuthClient is an autogenerated mock type for the OAuthClient type
type MockOAuthClient struct {
	mock.Mock
}

type MockOAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthClient) EXPECT() *MockOAuthClient_Expecter {
	return &MockOAuthClient_Expecter{mock: &_m.Mock}
}

// ExchangeCode provides a mock function for the type MockOAuthClient
func (_mock *MockOAuthClient) ExchangeCode(ctx context.Context, code string, codeVerifier string, redirectURI string) (*iracing.TokenResponse, error) {
	ret := _mock.Called(ctx, code, codeVerifier, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCode")
	}

	var r0 *iracing.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*iracing.TokenResponse, error)); ok {
		return returnFunc(ctx, code, codeVerifier, redirectURI)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *iracing.TokenResponse); ok {
		r0 = returnFunc(ctx, code, codeVerifier, redirectURI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iracing.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, code, codeVerifier, redirectURI)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthClient_ExchangeCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCode'
type MockOAuthClient_ExchangeCode_Call struct {
	*mock.Call
}

// ExchangeCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - codeVerifier string
//   - redirectURI string
func (_e *MockOAuthClient_Expecter) ExchangeCode(ctx interface{}, code interface{}, codeVerifier interface{}, redirectURI interface{}) *MockOAuthClient_ExchangeCode_Call {
	return &MockOAuthClient_ExchangeCode_Call{Call: _e.mock.On("ExchangeCode", ctx, code, codeVerifier, redirectURI)}
}

func (_c *MockOAuthClient_ExchangeCode_Call) Run(run func(ctx context.Context, code string, codeVerifier string, redirectURI string)) *MockOAuthClient_ExchangeCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOAuthClient_ExchangeCode_Call) Return(tokenResponse *iracing.TokenResponse, err error) *MockOAuthClient_ExchangeCode_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockOAuthClient_ExchangeCode_Call) RunAndReturn(run func(ctx context.Context, code string, codeVerifier string, redirectURI string) (*iracing.TokenResponse, error)) *MockOAuthClient_ExchangeCode_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockOAuthClient
func (_mock *MockOAuthClient) RefreshToken(ctx context.Context, refreshToken string) (*iracing.TokenResponse, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *iracing.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*iracing.TokenResponse, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *iracing.TokenResponse); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iracing.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthClient_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockOAuthClient_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockOAuthClient_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockOAuthClient_RefreshToken_Call {
	return &MockOAuthClient_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockOAuthClient_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockOAuthClient_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOAuthClient_RefreshToken_Call) Return(tokenResponse *iracing.TokenResponse, err error) *MockOAuthClient_RefreshToken_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockOAuthClient_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*iracing.TokenResponse, error)) *MockOAuthClient_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
