// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/jonsabados/saturdaysspinout/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDriverStore creates a new instance of MockDriverStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriverStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriverStore {
	mock := &MockDriverStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDriverStore is an autogenerated mock type for the DriverStore type
type MockDriverStore struct {
	mock.Mock
}

type MockDriverStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriverStore) EXPECT() *MockDriverStore_Expecter {
	return &MockDriverStore_Expecter{mock: &_m.Mock}
}

// GetDriver provides a mock function for the type MockDriverStore
func (_mock *MockDriverStore) GetDriver(ctx context.Context, driverID int64) (*store.Driver, error) {
	ret := _mock.Called(ctx, driverID)

	if len(ret) == 0 {
		panic("no return value specified for GetDriver")
	}

	var r0 *store.Driver
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*store.Driver, error)); ok {
		return returnFunc(ctx, driverID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *store.Driver); ok {
		r0 = returnFunc(ctx, driverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Driver)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, driverID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriverStore_GetDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriver'
type MockDriverStore_GetDriver_Call struct {
	*mock.Call
}

// GetDriver is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
func (_e *MockDriverStore_Expecter) GetDriver(ctx interface{}, driverID interface{}) *MockDriverStore_GetDriver_Call {
	return &MockDriverStore_GetDriver_Call{Call: _e.mock.On("GetDriver", ctx, driverID)}
}

func (_c *MockDriverStore_GetDriver_Call) Run(run func(ctx context.Context, driverID int64)) *MockDriverStore_GetDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDriverStore_GetDriver_Call) Return(driver *store.Driver, err error) *MockDriverStore_GetDriver_Call {
	_c.Call.Return(driver, err)
	return _c
}

func (_c *MockDriverStore_GetDriver_Call) RunAndReturn(run func(ctx context.Context, driverID int64) (*store.Driver, error)) *MockDriverStore_GetDriver_Call {
	_c.Call.Return(run)
	return _c
}

// InsertDriver provides a mock function for the type MockDriverStore
func (_mock *MockDriverStore) InsertDriver(ctx context.Context, driver store.Driver) error {
	ret := _mock.Called(ctx, driver)

	if len(ret) == 0 {
		panic("no return value specified for InsertDriver")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.Driver) error); ok {
		r0 = returnFunc(ctx, driver)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriverStore_InsertDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertDriver'
type MockDriverStore_InsertDriver_Call struct {
	*mock.Call
}

// InsertDriver is a helper method to define mock.On call
//   - ctx context.Context
//   - driver store.Driver
func (_e *MockDriverStore_Expecter) InsertDriver(ctx interface{}, driver interface{}) *MockDriverStore_InsertDriver_Call {
	return &MockDriverStore_InsertDriver_Call{Call: _e.mock.On("InsertDriver", ctx, driver)}
}

func (_c *MockDriverStore_InsertDriver_Call) Run(run func(ctx context.Context, driver store.Driver)) *MockDriverStore_InsertDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.Driver
		if args[1] != nil {
			arg1 = args[1].(store.Driver)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDriverStore_InsertDriver_Call) Return(err error) *MockDriverStore_InsertDriver_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriverStore_InsertDriver_Call) RunAndReturn(run func(ctx context.Context, driver store.Driver) error) *MockDriverStore_InsertDriver_Call {
	_c.Call.Return(run)
	return _c
}

// RecordLogin provides a mock function for the type MockDriverStore
func (_mock *MockDriverStore) RecordLogin(ctx context.Context, driverID int64, loginTime time.Time) error {
	ret := _mock.Called(ctx, driverID, loginTime)

	if len(ret) == 0 {
		panic("no return value specified for RecordLogin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time) error); ok {
		r0 = returnFunc(ctx, driverID, loginTime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriverStore_RecordLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordLogin'
type MockDriverStore_RecordLogin_Call struct {
	*mock.Call
}

// RecordLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - loginTime time.Time
func (_e *MockDriverStore_Expecter) RecordLogin(ctx interface{}, driverID interface{}, loginTime interface{}) *MockDriverStore_RecordLogin_Call {
	return &MockDriverStore_RecordLogin_Call{Call: _e.mock.On("RecordLogin", ctx, driverID, loginTime)}
}

func (_c *MockDriverStore_RecordLogin_Call) Run(run func(ctx context.Context, driverID int64, loginTime time.Time)) *MockDriverStore_RecordLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDriverStore_RecordLogin_Call) Return(err error) *MockDriverStore_RecordLogin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriverStore_RecordLogin_Call) RunAndReturn(run func(ctx context.Context, driverID int64, loginTime time.Time) error) *MockDriverStore_RecordLogin_Call {
	_c.Call.Return(run)
	return _c
}
