// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"crypto/ecdsa"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKMSSigner creates a new instance of MockKMSSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKMSSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKMSSigner {
	mock := &MockKMSSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKMSSigner is an autogenerated mock type for the KMSSigner type
type MockKMSSigner struct {
	mock.Mock
}

type MockKMSSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKMSSigner) EXPECT() *MockKMSSigner_Expecter {
	return &MockKMSSigner_Expecter{mock: &_m.Mock}
}

// GetPublicKey provides a mock function for the type MockKMSSigner
func (_mock *MockKMSSigner) GetPublicKey(ctx context.Context) (*ecdsa.PublicKey, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKey")
	}

	var r0 *ecdsa.PublicKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*ecdsa.PublicKey, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *ecdsa.PublicKey); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecdsa.PublicKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSSigner_GetPublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicKey'
type MockKMSSigner_GetPublicKey_Call struct {
	*mock.Call
}

// GetPublicKey is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKMSSigner_Expecter) GetPublicKey(ctx interface{}) *MockKMSSigner_GetPublicKey_Call {
	return &MockKMSSigner_GetPublicKey_Call{Call: _e.mock.On("GetPublicKey", ctx)}
}

func (_c *MockKMSSigner_GetPublicKey_Call) Run(run func(ctx context.Context)) *MockKMSSigner_GetPublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKMSSigner_GetPublicKey_Call) Return(publicKey *ecdsa.PublicKey, err error) *MockKMSSigner_GetPublicKey_Call {
	_c.Call.Return(publicKey, err)
	return _c
}

func (_c *MockKMSSigner_GetPublicKey_Call) RunAndReturn(run func(ctx context.Context) (*ecdsa.PublicKey, error)) *MockKMSSigner_GetPublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type MockKMSSigner
func (_mock *MockKMSSigner) Sign(ctx context.Context, digest []byte) ([]byte, error) {
	ret := _mock.Called(ctx, digest)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, digest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = returnFunc(ctx, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockKMSSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - ctx context.Context
//   - digest []byte
func (_e *MockKMSSigner_Expecter) Sign(ctx interface{}, digest interface{}) *MockKMSSigner_Sign_Call {
	return &MockKMSSigner_Sign_Call{Call: _e.mock.On("Sign", ctx, digest)}
}

func (_c *MockKMSSigner_Sign_Call) Run(run func(ctx context.Context, digest []byte)) *MockKMSSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKMSSigner_Sign_Call) Return(bytes []byte, err error) *MockKMSSigner_Sign_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKMSSigner_Sign_Call) RunAndReturn(run func(ctx context.Context, digest []byte) ([]byte, error)) *MockKMSSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}
