// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJWTCreator creates a new instance of MockJWTCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTCreator {
	mock := &MockJWTCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJWTCreator is an autogenerated mock type for the JWTCreator type
type MockJWTCreator struct {
	mock.Mock
}

type MockJWTCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTCreator) EXPECT() *MockJWTCreator_Expecter {
	return &MockJWTCreator_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function for the type MockJWTCreator
func (_mock *MockJWTCreator) CreateToken(ctx context.Context, userID int, userName string, accessToken string, refreshToken string, tokenExpiry time.Time) (string, error) {
	ret := _mock.Called(ctx, userID, userName, accessToken, refreshToken, tokenExpiry)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string, string, time.Time) (string, error)); ok {
		return returnFunc(ctx, userID, userName, accessToken, refreshToken, tokenExpiry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string, string, time.Time) string); ok {
		r0 = returnFunc(ctx, userID, userName, accessToken, refreshToken, tokenExpiry)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string, string, string, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, userName, accessToken, refreshToken, tokenExpiry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTCreator_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockJWTCreator_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - userName string
//   - accessToken string
//   - refreshToken string
//   - tokenExpiry time.Time
func (_e *MockJWTCreator_Expecter) CreateToken(ctx interface{}, userID interface{}, userName interface{}, accessToken interface{}, refreshToken interface{}, tokenExpiry interface{}) *MockJWTCreator_CreateToken_Call {
	return &MockJWTCreator_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, userID, userName, accessToken, refreshToken, tokenExpiry)}
}

func (_c *MockJWTCreator_CreateToken_Call) Run(run func(ctx context.Context, userID int, userName string, accessToken string, refreshToken string, tokenExpiry time.Time)) *MockJWTCreator_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockJWTCreator_CreateToken_Call) Return(s string, err error) *MockJWTCreator_CreateToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJWTCreator_CreateToken_Call) RunAndReturn(run func(ctx context.Context, userID int, userName string, accessToken string, refreshToken string, tokenExpiry time.Time) (string, error)) *MockJWTCreator_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}
