// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package iracing

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricsClient creates a new instance of MockMetricsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsClient {
	mock := &MockMetricsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsClient is an autogenerated mock type for the MetricsClient type
type MockMetricsClient struct {
	mock.Mock
}

type MockMetricsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsClient) EXPECT() *MockMetricsClient_Expecter {
	return &MockMetricsClient_Expecter{mock: &_m.Mock}
}

// EmitGauge provides a mock function for the type MockMetricsClient
func (_mock *MockMetricsClient) EmitGauge(ctx context.Context, name string, value float64) error {
	ret := _mock.Called(ctx, name, value)

	if len(ret) == 0 {
		panic("no return value specified for EmitGauge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = returnFunc(ctx, name, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsClient_EmitGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitGauge'
type MockMetricsClient_EmitGauge_Call struct {
	*mock.Call
}

// EmitGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - value float64
func (_e *MockMetricsClient_Expecter) EmitGauge(ctx interface{}, name interface{}, value interface{}) *MockMetricsClient_EmitGauge_Call {
	return &MockMetricsClient_EmitGauge_Call{Call: _e.mock.On("EmitGauge", ctx, name, value)}
}

func (_c *MockMetricsClient_EmitGauge_Call) Run(run func(ctx context.Context, name string, value float64)) *MockMetricsClient_EmitGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetricsClient_EmitGauge_Call) Return(err error) *MockMetricsClient_EmitGauge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsClient_EmitGauge_Call) RunAndReturn(run func(ctx context.Context, name string, value float64) error) *MockMetricsClient_EmitGauge_Call {
	_c.Call.Return(run)
	return _c
}
