// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package iracing

import (
	"net/url"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSearchOption creates a new instance of MockSearchOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchOption {
	mock := &MockSearchOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearchOption is an autogenerated mock type for the SearchOption type
type MockSearchOption struct {
	mock.Mock
}

type MockSearchOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchOption) EXPECT() *MockSearchOption_Expecter {
	return &MockSearchOption_Expecter{mock: &_m.Mock}
}

// applySearch provides a mock function for the type MockSearchOption
func (_mock *MockSearchOption) applySearch(params url.Values) {
	_mock.Called(params)
	return
}

// MockSearchOption_applySearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applySearch'
type MockSearchOption_applySearch_Call struct {
	*mock.Call
}

// applySearch is a helper method to define mock.On call
//   - params url.Values
func (_e *MockSearchOption_Expecter) applySearch(params interface{}) *MockSearchOption_applySearch_Call {
	return &MockSearchOption_applySearch_Call{Call: _e.mock.On("applySearch", params)}
}

func (_c *MockSearchOption_applySearch_Call) Run(run func(params url.Values)) *MockSearchOption_applySearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 url.Values
		if args[0] != nil {
			arg0 = args[0].(url.Values)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSearchOption_applySearch_Call) Return() *MockSearchOption_applySearch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSearchOption_applySearch_Call) RunAndReturn(run func(params url.Values)) *MockSearchOption_applySearch_Call {
	_c.Run(run)
	return _c
}
