// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package iracing

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetUserInfo provides a mock function for the type MockClient
func (_mock *MockClient) GetUserInfo(ctx context.Context, accessToken string) (*UserInfo, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*UserInfo, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *UserInfo); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockClient_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockClient_Expecter) GetUserInfo(ctx interface{}, accessToken interface{}) *MockClient_GetUserInfo_Call {
	return &MockClient_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, accessToken)}
}

func (_c *MockClient_GetUserInfo_Call) Run(run func(ctx context.Context, accessToken string)) *MockClient_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetUserInfo_Call) Return(userInfo *UserInfo, err error) *MockClient_GetUserInfo_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockClient_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (*UserInfo, error)) *MockClient_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}
