// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package iracing

import (
	"net/url"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGetLapDataOption creates a new instance of MockGetLapDataOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetLapDataOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetLapDataOption {
	mock := &MockGetLapDataOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetLapDataOption is an autogenerated mock type for the GetLapDataOption type
type MockGetLapDataOption struct {
	mock.Mock
}

type MockGetLapDataOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetLapDataOption) EXPECT() *MockGetLapDataOption_Expecter {
	return &MockGetLapDataOption_Expecter{mock: &_m.Mock}
}

// applyGetLapData provides a mock function for the type MockGetLapDataOption
func (_mock *MockGetLapDataOption) applyGetLapData(params url.Values) {
	_mock.Called(params)
	return
}

// MockGetLapDataOption_applyGetLapData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyGetLapData'
type MockGetLapDataOption_applyGetLapData_Call struct {
	*mock.Call
}

// applyGetLapData is a helper method to define mock.On call
//   - params url.Values
func (_e *MockGetLapDataOption_Expecter) applyGetLapData(params interface{}) *MockGetLapDataOption_applyGetLapData_Call {
	return &MockGetLapDataOption_applyGetLapData_Call{Call: _e.mock.On("applyGetLapData", params)}
}

func (_c *MockGetLapDataOption_applyGetLapData_Call) Run(run func(params url.Values)) *MockGetLapDataOption_applyGetLapData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 url.Values
		if args[0] != nil {
			arg0 = args[0].(url.Values)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGetLapDataOption_applyGetLapData_Call) Return() *MockGetLapDataOption_applyGetLapData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGetLapDataOption_applyGetLapData_Call) RunAndReturn(run func(params url.Values)) *MockGetLapDataOption_applyGetLapData_Call {
	_c.Run(run)
	return _c
}
