// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tracks

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/iracing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIRacingClient creates a new instance of MockIRacingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRacingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRacingClient {
	mock := &MockIRacingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRacingClient is an autogenerated mock type for the IRacingClient type
type MockIRacingClient struct {
	mock.Mock
}

type MockIRacingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRacingClient) EXPECT() *MockIRacingClient_Expecter {
	return &MockIRacingClient_Expecter{mock: &_m.Mock}
}

// GetTrackAssets provides a mock function for the type MockIRacingClient
func (_mock *MockIRacingClient) GetTrackAssets(ctx context.Context, accessToken string) (map[int64]iracing.TrackAssets, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetTrackAssets")
	}

	var r0 map[int64]iracing.TrackAssets
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[int64]iracing.TrackAssets, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[int64]iracing.TrackAssets); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]iracing.TrackAssets)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRacingClient_GetTrackAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrackAssets'
type MockIRacingClient_GetTrackAssets_Call struct {
	*mock.Call
}

// GetTrackAssets is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockIRacingClient_Expecter) GetTrackAssets(ctx interface{}, accessToken interface{}) *MockIRacingClient_GetTrackAssets_Call {
	return &MockIRacingClient_GetTrackAssets_Call{Call: _e.mock.On("GetTrackAssets", ctx, accessToken)}
}

func (_c *MockIRacingClient_GetTrackAssets_Call) Run(run func(ctx context.Context, accessToken string)) *MockIRacingClient_GetTrackAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRacingClient_GetTrackAssets_Call) Return(int64ToTrackAssets map[int64]iracing.TrackAssets, err error) *MockIRacingClient_GetTrackAssets_Call {
	_c.Call.Return(int64ToTrackAssets, err)
	return _c
}

func (_c *MockIRacingClient_GetTrackAssets_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (map[int64]iracing.TrackAssets, error)) *MockIRacingClient_GetTrackAssets_Call {
	_c.Call.Return(run)
	return _c
}

// GetTracks provides a mock function for the type MockIRacingClient
func (_mock *MockIRacingClient) GetTracks(ctx context.Context, accessToken string) ([]iracing.TrackInfo, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetTracks")
	}

	var r0 []iracing.TrackInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]iracing.TrackInfo, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []iracing.TrackInfo); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iracing.TrackInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRacingClient_GetTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTracks'
type MockIRacingClient_GetTracks_Call struct {
	*mock.Call
}

// GetTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockIRacingClient_Expecter) GetTracks(ctx interface{}, accessToken interface{}) *MockIRacingClient_GetTracks_Call {
	return &MockIRacingClient_GetTracks_Call{Call: _e.mock.On("GetTracks", ctx, accessToken)}
}

func (_c *MockIRacingClient_GetTracks_Call) Run(run func(ctx context.Context, accessToken string)) *MockIRacingClient_GetTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRacingClient_GetTracks_Call) Return(trackInfos []iracing.TrackInfo, err error) *MockIRacingClient_GetTracks_Call {
	_c.Call.Return(trackInfos, err)
	return _c
}

func (_c *MockIRacingClient_GetTracks_Call) RunAndReturn(run func(ctx context.Context, accessToken string) ([]iracing.TrackInfo, error)) *MockIRacingClient_GetTracks_Call {
	_c.Call.Return(run)
	return _c
}
