// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package analytics

import (
	"context"
	"time"

	"github.com/jonsabados/saturdaysspinout/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// GetDriverSessionsByTimeRange provides a mock function for the type MockStore
func (_mock *MockStore) GetDriverSessionsByTimeRange(ctx context.Context, driverID int64, from time.Time, to time.Time, filters ...store.SessionFilter) ([]store.DriverSession, error) {
	var tmpRet mock.Arguments
	if len(filters) > 0 {
		tmpRet = _mock.Called(ctx, driverID, from, to, filters)
	} else {
		tmpRet = _mock.Called(ctx, driverID, from, to)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetDriverSessionsByTimeRange")
	}

	var r0 []store.DriverSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time, ...store.SessionFilter) ([]store.DriverSession, error)); ok {
		return returnFunc(ctx, driverID, from, to, filters...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time, ...store.SessionFilter) []store.DriverSession); ok {
		r0 = returnFunc(ctx, driverID, from, to, filters...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.DriverSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time, ...store.SessionFilter) error); ok {
		r1 = returnFunc(ctx, driverID, from, to, filters...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetDriverSessionsByTimeRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriverSessionsByTimeRange'
type MockStore_GetDriverSessionsByTimeRange_Call struct {
	*mock.Call
}

// GetDriverSessionsByTimeRange is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - from time.Time
//   - to time.Time
//   - filters ...store.SessionFilter
func (_e *MockStore_Expecter) GetDriverSessionsByTimeRange(ctx interface{}, driverID interface{}, from interface{}, to interface{}, filters ...interface{}) *MockStore_GetDriverSessionsByTimeRange_Call {
	return &MockStore_GetDriverSessionsByTimeRange_Call{Call: _e.mock.On("GetDriverSessionsByTimeRange",
		append([]interface{}{ctx, driverID, from, to}, filters...)...)}
}

func (_c *MockStore_GetDriverSessionsByTimeRange_Call) Run(run func(ctx context.Context, driverID int64, from time.Time, to time.Time, filters ...store.SessionFilter)) *MockStore_GetDriverSessionsByTimeRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 []store.SessionFilter
		var variadicArgs []store.SessionFilter
		if len(args) > 4 {
			variadicArgs = args[4].([]store.SessionFilter)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockStore_GetDriverSessionsByTimeRange_Call) Return(driverSessions []store.DriverSession, err error) *MockStore_GetDriverSessionsByTimeRange_Call {
	_c.Call.Return(driverSessions, err)
	return _c
}

func (_c *MockStore_GetDriverSessionsByTimeRange_Call) RunAndReturn(run func(ctx context.Context, driverID int64, from time.Time, to time.Time, filters ...store.SessionFilter) ([]store.DriverSession, error)) *MockStore_GetDriverSessionsByTimeRange_Call {
	_c.Call.Return(run)
	return _c
}
