// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cars

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/cars"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCarsService creates a new instance of MockCarsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarsService {
	mock := &MockCarsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCarsService is an autogenerated mock type for the CarsService type
type MockCarsService struct {
	mock.Mock
}

type MockCarsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarsService) EXPECT() *MockCarsService_Expecter {
	return &MockCarsService_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockCarsService
func (_mock *MockCarsService) GetAll(ctx context.Context, accessToken string) ([]cars.Car, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []cars.Car
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]cars.Car, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []cars.Car); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cars.Car)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarsService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockCarsService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockCarsService_Expecter) GetAll(ctx interface{}, accessToken interface{}) *MockCarsService_GetAll_Call {
	return &MockCarsService_GetAll_Call{Call: _e.mock.On("GetAll", ctx, accessToken)}
}

func (_c *MockCarsService_GetAll_Call) Run(run func(ctx context.Context, accessToken string)) *MockCarsService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarsService_GetAll_Call) Return(cars1 []cars.Car, err error) *MockCarsService_GetAll_Call {
	_c.Call.Return(cars1, err)
	return _c
}

func (_c *MockCarsService_GetAll_Call) RunAndReturn(run func(ctx context.Context, accessToken string) ([]cars.Car, error)) *MockCarsService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
