all: false
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceName | snakecase}}.go"
formatter: goimports
pkgname: mocks
structname: "Mock{{.InterfaceName}}"
template: testify
packages:
  github.com/jonsabados/saturdaysspinout/auth:
    interfaces:
      KMSSigner:
      KMSEncryptor:
      KMSClient:
      AWSKMS: