dir: "{{.InterfaceDir}}"
filename: "mock_{{.InterfaceName | snakecase}}_test.go"
formatter: goimports
inpackage: true
structname: "Mock{{.InterfaceName}}"
template: testify
recursive: true
packages:
  github.com/jonsabados/saturdaysspinout:
    config:
      all: true