// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ingestion

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPusher creates a new instance of MockPusher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPusher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPusher {
	mock := &MockPusher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPusher is an autogenerated mock type for the Pusher type
type MockPusher struct {
	mock.Mock
}

type MockPusher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPusher) EXPECT() *MockPusher_Expecter {
	return &MockPusher_Expecter{mock: &_m.Mock}
}

// Broadcast provides a mock function for the type MockPusher
func (_mock *MockPusher) Broadcast(ctx context.Context, driverID int64, actionType string, payload any) error {
	ret := _mock.Called(ctx, driverID, actionType, payload)

	if len(ret) == 0 {
		panic("no return value specified for Broadcast")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, any) error); ok {
		r0 = returnFunc(ctx, driverID, actionType, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPusher_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type MockPusher_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - actionType string
//   - payload any
func (_e *MockPusher_Expecter) Broadcast(ctx interface{}, driverID interface{}, actionType interface{}, payload interface{}) *MockPusher_Broadcast_Call {
	return &MockPusher_Broadcast_Call{Call: _e.mock.On("Broadcast", ctx, driverID, actionType, payload)}
}

func (_c *MockPusher_Broadcast_Call) Run(run func(ctx context.Context, driverID int64, actionType string, payload any)) *MockPusher_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPusher_Broadcast_Call) Return(err error) *MockPusher_Broadcast_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPusher_Broadcast_Call) RunAndReturn(run func(ctx context.Context, driverID int64, actionType string, payload any) error) *MockPusher_Broadcast_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockPusher
func (_mock *MockPusher) Push(ctx context.Context, connectionID string, actionType string, payload any) (bool, error) {
	ret := _mock.Called(ctx, connectionID, actionType, payload)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any) (bool, error)); ok {
		return returnFunc(ctx, connectionID, actionType, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any) bool); ok {
		r0 = returnFunc(ctx, connectionID, actionType, payload)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, any) error); ok {
		r1 = returnFunc(ctx, connectionID, actionType, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPusher_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockPusher_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID string
//   - actionType string
//   - payload any
func (_e *MockPusher_Expecter) Push(ctx interface{}, connectionID interface{}, actionType interface{}, payload interface{}) *MockPusher_Push_Call {
	return &MockPusher_Push_Call{Call: _e.mock.On("Push", ctx, connectionID, actionType, payload)}
}

func (_c *MockPusher_Push_Call) Run(run func(ctx context.Context, connectionID string, actionType string, payload any)) *MockPusher_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPusher_Push_Call) Return(b bool, err error) *MockPusher_Push_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPusher_Push_Call) RunAndReturn(run func(ctx context.Context, connectionID string, actionType string, payload any) (bool, error)) *MockPusher_Push_Call {
	_c.Call.Return(run)
	return _c
}
