// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ingestion

import (
	"context"
	"time"

	"github.com/jonsabados/saturdaysspinout/iracing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIRacingClient creates a new instance of MockIRacingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRacingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRacingClient {
	mock := &MockIRacingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRacingClient is an autogenerated mock type for the IRacingClient type
type MockIRacingClient struct {
	mock.Mock
}

type MockIRacingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRacingClient) EXPECT() *MockIRacingClient_Expecter {
	return &MockIRacingClient_Expecter{mock: &_m.Mock}
}

// GetLapData provides a mock function for the type MockIRacingClient
func (_mock *MockIRacingClient) GetLapData(ctx context.Context, accessToken string, subsessionID int64, simsessionNumber int, opts ...iracing.GetLapDataOption) (*iracing.LapDataResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, accessToken, subsessionID, simsessionNumber, opts)
	} else {
		tmpRet = _mock.Called(ctx, accessToken, subsessionID, simsessionNumber)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetLapData")
	}

	var r0 *iracing.LapDataResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int, ...iracing.GetLapDataOption) (*iracing.LapDataResponse, error)); ok {
		return returnFunc(ctx, accessToken, subsessionID, simsessionNumber, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int, ...iracing.GetLapDataOption) *iracing.LapDataResponse); ok {
		r0 = returnFunc(ctx, accessToken, subsessionID, simsessionNumber, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iracing.LapDataResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int, ...iracing.GetLapDataOption) error); ok {
		r1 = returnFunc(ctx, accessToken, subsessionID, simsessionNumber, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRacingClient_GetLapData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLapData'
type MockIRacingClient_GetLapData_Call struct {
	*mock.Call
}

// GetLapData is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - subsessionID int64
//   - simsessionNumber int
//   - opts ...iracing.GetLapDataOption
func (_e *MockIRacingClient_Expecter) GetLapData(ctx interface{}, accessToken interface{}, subsessionID interface{}, simsessionNumber interface{}, opts ...interface{}) *MockIRacingClient_GetLapData_Call {
	return &MockIRacingClient_GetLapData_Call{Call: _e.mock.On("GetLapData",
		append([]interface{}{ctx, accessToken, subsessionID, simsessionNumber}, opts...)...)}
}

func (_c *MockIRacingClient_GetLapData_Call) Run(run func(ctx context.Context, accessToken string, subsessionID int64, simsessionNumber int, opts ...iracing.GetLapDataOption)) *MockIRacingClient_GetLapData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []iracing.GetLapDataOption
		var variadicArgs []iracing.GetLapDataOption
		if len(args) > 4 {
			variadicArgs = args[4].([]iracing.GetLapDataOption)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockIRacingClient_GetLapData_Call) Return(lapDataResponse *iracing.LapDataResponse, err error) *MockIRacingClient_GetLapData_Call {
	_c.Call.Return(lapDataResponse, err)
	return _c
}

func (_c *MockIRacingClient_GetLapData_Call) RunAndReturn(run func(ctx context.Context, accessToken string, subsessionID int64, simsessionNumber int, opts ...iracing.GetLapDataOption) (*iracing.LapDataResponse, error)) *MockIRacingClient_GetLapData_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionResults provides a mock function for the type MockIRacingClient
func (_mock *MockIRacingClient) GetSessionResults(ctx context.Context, accessToken string, subsessionID int64, opts ...iracing.GetSessionResultsOption) (*iracing.SessionResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, accessToken, subsessionID, opts)
	} else {
		tmpRet = _mock.Called(ctx, accessToken, subsessionID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSessionResults")
	}

	var r0 *iracing.SessionResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, ...iracing.GetSessionResultsOption) (*iracing.SessionResult, error)); ok {
		return returnFunc(ctx, accessToken, subsessionID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, ...iracing.GetSessionResultsOption) *iracing.SessionResult); ok {
		r0 = returnFunc(ctx, accessToken, subsessionID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iracing.SessionResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, ...iracing.GetSessionResultsOption) error); ok {
		r1 = returnFunc(ctx, accessToken, subsessionID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRacingClient_GetSessionResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionResults'
type MockIRacingClient_GetSessionResults_Call struct {
	*mock.Call
}

// GetSessionResults is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - subsessionID int64
//   - opts ...iracing.GetSessionResultsOption
func (_e *MockIRacingClient_Expecter) GetSessionResults(ctx interface{}, accessToken interface{}, subsessionID interface{}, opts ...interface{}) *MockIRacingClient_GetSessionResults_Call {
	return &MockIRacingClient_GetSessionResults_Call{Call: _e.mock.On("GetSessionResults",
		append([]interface{}{ctx, accessToken, subsessionID}, opts...)...)}
}

func (_c *MockIRacingClient_GetSessionResults_Call) Run(run func(ctx context.Context, accessToken string, subsessionID int64, opts ...iracing.GetSessionResultsOption)) *MockIRacingClient_GetSessionResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 []iracing.GetSessionResultsOption
		var variadicArgs []iracing.GetSessionResultsOption
		if len(args) > 3 {
			variadicArgs = args[3].([]iracing.GetSessionResultsOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockIRacingClient_GetSessionResults_Call) Return(sessionResult *iracing.SessionResult, err error) *MockIRacingClient_GetSessionResults_Call {
	_c.Call.Return(sessionResult, err)
	return _c
}

func (_c *MockIRacingClient_GetSessionResults_Call) RunAndReturn(run func(ctx context.Context, accessToken string, subsessionID int64, opts ...iracing.GetSessionResultsOption) (*iracing.SessionResult, error)) *MockIRacingClient_GetSessionResults_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSeriesResults provides a mock function for the type MockIRacingClient
func (_mock *MockIRacingClient) SearchSeriesResults(ctx context.Context, accessToken string, finishRangeBegin time.Time, finishRangeEnd time.Time, opts ...iracing.SearchOption) ([]iracing.SeriesResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, accessToken, finishRangeBegin, finishRangeEnd, opts)
	} else {
		tmpRet = _mock.Called(ctx, accessToken, finishRangeBegin, finishRangeEnd)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SearchSeriesResults")
	}

	var r0 []iracing.SeriesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, ...iracing.SearchOption) ([]iracing.SeriesResult, error)); ok {
		return returnFunc(ctx, accessToken, finishRangeBegin, finishRangeEnd, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, ...iracing.SearchOption) []iracing.SeriesResult); ok {
		r0 = returnFunc(ctx, accessToken, finishRangeBegin, finishRangeEnd, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iracing.SeriesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, ...iracing.SearchOption) error); ok {
		r1 = returnFunc(ctx, accessToken, finishRangeBegin, finishRangeEnd, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRacingClient_SearchSeriesResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSeriesResults'
type MockIRacingClient_SearchSeriesResults_Call struct {
	*mock.Call
}

// SearchSeriesResults is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - finishRangeBegin time.Time
//   - finishRangeEnd time.Time
//   - opts ...iracing.SearchOption
func (_e *MockIRacingClient_Expecter) SearchSeriesResults(ctx interface{}, accessToken interface{}, finishRangeBegin interface{}, finishRangeEnd interface{}, opts ...interface{}) *MockIRacingClient_SearchSeriesResults_Call {
	return &MockIRacingClient_SearchSeriesResults_Call{Call: _e.mock.On("SearchSeriesResults",
		append([]interface{}{ctx, accessToken, finishRangeBegin, finishRangeEnd}, opts...)...)}
}

func (_c *MockIRacingClient_SearchSeriesResults_Call) Run(run func(ctx context.Context, accessToken string, finishRangeBegin time.Time, finishRangeEnd time.Time, opts ...iracing.SearchOption)) *MockIRacingClient_SearchSeriesResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 []iracing.SearchOption
		var variadicArgs []iracing.SearchOption
		if len(args) > 4 {
			variadicArgs = args[4].([]iracing.SearchOption)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockIRacingClient_SearchSeriesResults_Call) Return(seriesResults []iracing.SeriesResult, err error) *MockIRacingClient_SearchSeriesResults_Call {
	_c.Call.Return(seriesResults, err)
	return _c
}

func (_c *MockIRacingClient_SearchSeriesResults_Call) RunAndReturn(run func(ctx context.Context, accessToken string, finishRangeBegin time.Time, finishRangeEnd time.Time, opts ...iracing.SearchOption) ([]iracing.SeriesResult, error)) *MockIRacingClient_SearchSeriesResults_Call {
	_c.Call.Return(run)
	return _c
}
