// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ingestion

import (
	"context"
	"time"

	"github.com/jonsabados/saturdaysspinout/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// AcquireIngestionLock provides a mock function for the type MockStore
func (_mock *MockStore) AcquireIngestionLock(ctx context.Context, driverID int64, lockDuration time.Duration) (bool, error) {
	ret := _mock.Called(ctx, driverID, lockDuration)

	if len(ret) == 0 {
		panic("no return value specified for AcquireIngestionLock")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, driverID, lockDuration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Duration) bool); ok {
		r0 = returnFunc(ctx, driverID, lockDuration)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Duration) error); ok {
		r1 = returnFunc(ctx, driverID, lockDuration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_AcquireIngestionLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireIngestionLock'
type MockStore_AcquireIngestionLock_Call struct {
	*mock.Call
}

// AcquireIngestionLock is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - lockDuration time.Duration
func (_e *MockStore_Expecter) AcquireIngestionLock(ctx interface{}, driverID interface{}, lockDuration interface{}) *MockStore_AcquireIngestionLock_Call {
	return &MockStore_AcquireIngestionLock_Call{Call: _e.mock.On("AcquireIngestionLock", ctx, driverID, lockDuration)}
}

func (_c *MockStore_AcquireIngestionLock_Call) Run(run func(ctx context.Context, driverID int64, lockDuration time.Duration)) *MockStore_AcquireIngestionLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_AcquireIngestionLock_Call) Return(b bool, err error) *MockStore_AcquireIngestionLock_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStore_AcquireIngestionLock_Call) RunAndReturn(run func(ctx context.Context, driverID int64, lockDuration time.Duration) (bool, error)) *MockStore_AcquireIngestionLock_Call {
	_c.Call.Return(run)
	return _c
}

// GetDriver provides a mock function for the type MockStore
func (_mock *MockStore) GetDriver(ctx context.Context, driverID int64) (*store.Driver, error) {
	ret := _mock.Called(ctx, driverID)

	if len(ret) == 0 {
		panic("no return value specified for GetDriver")
	}

	var r0 *store.Driver
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*store.Driver, error)); ok {
		return returnFunc(ctx, driverID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *store.Driver); ok {
		r0 = returnFunc(ctx, driverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Driver)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, driverID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriver'
type MockStore_GetDriver_Call struct {
	*mock.Call
}

// GetDriver is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
func (_e *MockStore_Expecter) GetDriver(ctx interface{}, driverID interface{}) *MockStore_GetDriver_Call {
	return &MockStore_GetDriver_Call{Call: _e.mock.On("GetDriver", ctx, driverID)}
}

func (_c *MockStore_GetDriver_Call) Run(run func(ctx context.Context, driverID int64)) *MockStore_GetDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetDriver_Call) Return(driver *store.Driver, err error) *MockStore_GetDriver_Call {
	_c.Call.Return(driver, err)
	return _c
}

func (_c *MockStore_GetDriver_Call) RunAndReturn(run func(ctx context.Context, driverID int64) (*store.Driver, error)) *MockStore_GetDriver_Call {
	_c.Call.Return(run)
	return _c
}

// GetDriverSession provides a mock function for the type MockStore
func (_mock *MockStore) GetDriverSession(ctx context.Context, driverID int64, startTime time.Time) (*store.DriverSession, error) {
	ret := _mock.Called(ctx, driverID, startTime)

	if len(ret) == 0 {
		panic("no return value specified for GetDriverSession")
	}

	var r0 *store.DriverSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time) (*store.DriverSession, error)); ok {
		return returnFunc(ctx, driverID, startTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time) *store.DriverSession); ok {
		r0 = returnFunc(ctx, driverID, startTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.DriverSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time) error); ok {
		r1 = returnFunc(ctx, driverID, startTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetDriverSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriverSession'
type MockStore_GetDriverSession_Call struct {
	*mock.Call
}

// GetDriverSession is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - startTime time.Time
func (_e *MockStore_Expecter) GetDriverSession(ctx interface{}, driverID interface{}, startTime interface{}) *MockStore_GetDriverSession_Call {
	return &MockStore_GetDriverSession_Call{Call: _e.mock.On("GetDriverSession", ctx, driverID, startTime)}
}

func (_c *MockStore_GetDriverSession_Call) Run(run func(ctx context.Context, driverID int64, startTime time.Time)) *MockStore_GetDriverSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetDriverSession_Call) Return(driverSession *store.DriverSession, err error) *MockStore_GetDriverSession_Call {
	_c.Call.Return(driverSession, err)
	return _c
}

func (_c *MockStore_GetDriverSession_Call) RunAndReturn(run func(ctx context.Context, driverID int64, startTime time.Time) (*store.DriverSession, error)) *MockStore_GetDriverSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockStore
func (_mock *MockStore) GetSession(ctx context.Context, subsessionID int64) (*store.Session, error) {
	ret := _mock.Called(ctx, subsessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *store.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*store.Session, error)); ok {
		return returnFunc(ctx, subsessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *store.Session); ok {
		r0 = returnFunc(ctx, subsessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, subsessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockStore_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - subsessionID int64
func (_e *MockStore_Expecter) GetSession(ctx interface{}, subsessionID interface{}) *MockStore_GetSession_Call {
	return &MockStore_GetSession_Call{Call: _e.mock.On("GetSession", ctx, subsessionID)}
}

func (_c *MockStore_GetSession_Call) Run(run func(ctx context.Context, subsessionID int64)) *MockStore_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetSession_Call) Return(session *store.Session, err error) *MockStore_GetSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockStore_GetSession_Call) RunAndReturn(run func(ctx context.Context, subsessionID int64) (*store.Session, error)) *MockStore_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionDrivers provides a mock function for the type MockStore
func (_mock *MockStore) GetSessionDrivers(ctx context.Context, subsessionID int64) ([]store.SessionDriver, error) {
	ret := _mock.Called(ctx, subsessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionDrivers")
	}

	var r0 []store.SessionDriver
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]store.SessionDriver, error)); ok {
		return returnFunc(ctx, subsessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []store.SessionDriver); ok {
		r0 = returnFunc(ctx, subsessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.SessionDriver)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, subsessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetSessionDrivers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionDrivers'
type MockStore_GetSessionDrivers_Call struct {
	*mock.Call
}

// GetSessionDrivers is a helper method to define mock.On call
//   - ctx context.Context
//   - subsessionID int64
func (_e *MockStore_Expecter) GetSessionDrivers(ctx interface{}, subsessionID interface{}) *MockStore_GetSessionDrivers_Call {
	return &MockStore_GetSessionDrivers_Call{Call: _e.mock.On("GetSessionDrivers", ctx, subsessionID)}
}

func (_c *MockStore_GetSessionDrivers_Call) Run(run func(ctx context.Context, subsessionID int64)) *MockStore_GetSessionDrivers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetSessionDrivers_Call) Return(sessionDrivers []store.SessionDriver, err error) *MockStore_GetSessionDrivers_Call {
	_c.Call.Return(sessionDrivers, err)
	return _c
}

func (_c *MockStore_GetSessionDrivers_Call) RunAndReturn(run func(ctx context.Context, subsessionID int64) ([]store.SessionDriver, error)) *MockStore_GetSessionDrivers_Call {
	_c.Call.Return(run)
	return _c
}

// PersistSessionData provides a mock function for the type MockStore
func (_mock *MockStore) PersistSessionData(ctx context.Context, data store.SessionDataInsertion) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for PersistSessionData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.SessionDataInsertion) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_PersistSessionData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistSessionData'
type MockStore_PersistSessionData_Call struct {
	*mock.Call
}

// PersistSessionData is a helper method to define mock.On call
//   - ctx context.Context
//   - data store.SessionDataInsertion
func (_e *MockStore_Expecter) PersistSessionData(ctx interface{}, data interface{}) *MockStore_PersistSessionData_Call {
	return &MockStore_PersistSessionData_Call{Call: _e.mock.On("PersistSessionData", ctx, data)}
}

func (_c *MockStore_PersistSessionData_Call) Run(run func(ctx context.Context, data store.SessionDataInsertion)) *MockStore_PersistSessionData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.SessionDataInsertion
		if args[1] != nil {
			arg1 = args[1].(store.SessionDataInsertion)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PersistSessionData_Call) Return(err error) *MockStore_PersistSessionData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_PersistSessionData_Call) RunAndReturn(run func(ctx context.Context, data store.SessionDataInsertion) error) *MockStore_PersistSessionData_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseIngestionLock provides a mock function for the type MockStore
func (_mock *MockStore) ReleaseIngestionLock(ctx context.Context, driverID int64) error {
	ret := _mock.Called(ctx, driverID)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseIngestionLock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, driverID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_ReleaseIngestionLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseIngestionLock'
type MockStore_ReleaseIngestionLock_Call struct {
	*mock.Call
}

// ReleaseIngestionLock is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
func (_e *MockStore_Expecter) ReleaseIngestionLock(ctx interface{}, driverID interface{}) *MockStore_ReleaseIngestionLock_Call {
	return &MockStore_ReleaseIngestionLock_Call{Call: _e.mock.On("ReleaseIngestionLock", ctx, driverID)}
}

func (_c *MockStore_ReleaseIngestionLock_Call) Run(run func(ctx context.Context, driverID int64)) *MockStore_ReleaseIngestionLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ReleaseIngestionLock_Call) Return(err error) *MockStore_ReleaseIngestionLock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_ReleaseIngestionLock_Call) RunAndReturn(run func(ctx context.Context, driverID int64) error) *MockStore_ReleaseIngestionLock_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDriverRacesIngestedTo provides a mock function for the type MockStore
func (_mock *MockStore) UpdateDriverRacesIngestedTo(ctx context.Context, driverID int64, racesIngestedTo time.Time) error {
	ret := _mock.Called(ctx, driverID, racesIngestedTo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDriverRacesIngestedTo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time) error); ok {
		r0 = returnFunc(ctx, driverID, racesIngestedTo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_UpdateDriverRacesIngestedTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDriverRacesIngestedTo'
type MockStore_UpdateDriverRacesIngestedTo_Call struct {
	*mock.Call
}

// UpdateDriverRacesIngestedTo is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - racesIngestedTo time.Time
func (_e *MockStore_Expecter) UpdateDriverRacesIngestedTo(ctx interface{}, driverID interface{}, racesIngestedTo interface{}) *MockStore_UpdateDriverRacesIngestedTo_Call {
	return &MockStore_UpdateDriverRacesIngestedTo_Call{Call: _e.mock.On("UpdateDriverRacesIngestedTo", ctx, driverID, racesIngestedTo)}
}

func (_c *MockStore_UpdateDriverRacesIngestedTo_Call) Run(run func(ctx context.Context, driverID int64, racesIngestedTo time.Time)) *MockStore_UpdateDriverRacesIngestedTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_UpdateDriverRacesIngestedTo_Call) Return(err error) *MockStore_UpdateDriverRacesIngestedTo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_UpdateDriverRacesIngestedTo_Call) RunAndReturn(run func(ctx context.Context, driverID int64, racesIngestedTo time.Time) error) *MockStore_UpdateDriverRacesIngestedTo_Call {
	_c.Call.Return(run)
	return _c
}
