// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package developer

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFetcher creates a new instance of MockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcher {
	mock := &MockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFetcher is an autogenerated mock type for the Fetcher type
type MockFetcher struct {
	mock.Mock
}

type MockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcher) EXPECT() *MockFetcher_Expecter {
	return &MockFetcher_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockFetcher
func (_mock *MockFetcher) Fetch(ctx context.Context, accessToken string, path string) ([]byte, string, error) {
	ret := _mock.Called(ctx, accessToken, path)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, string, error)); ok {
		return returnFunc(ctx, accessToken, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = returnFunc(ctx, accessToken, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, accessToken, path)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, accessToken, path)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockFetcher_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - path string
func (_e *MockFetcher_Expecter) Fetch(ctx interface{}, accessToken interface{}, path interface{}) *MockFetcher_Fetch_Call {
	return &MockFetcher_Fetch_Call{Call: _e.mock.On("Fetch", ctx, accessToken, path)}
}

func (_c *MockFetcher_Fetch_Call) Run(run func(ctx context.Context, accessToken string, path string)) *MockFetcher_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFetcher_Fetch_Call) Return(bytes []byte, s string, err error) *MockFetcher_Fetch_Call {
	_c.Call.Return(bytes, s, err)
	return _c
}

func (_c *MockFetcher_Fetch_Call) RunAndReturn(run func(ctx context.Context, accessToken string, path string) ([]byte, string, error)) *MockFetcher_Fetch_Call {
	_c.Call.Return(run)
	return _c
}
