// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package disconnect

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionStore creates a new instance of MockConnectionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionStore {
	mock := &MockConnectionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionStore is an autogenerated mock type for the ConnectionStore type
type MockConnectionStore struct {
	mock.Mock
}

type MockConnectionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionStore) EXPECT() *MockConnectionStore_Expecter {
	return &MockConnectionStore_Expecter{mock: &_m.Mock}
}

// DeleteConnection provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) DeleteConnection(ctx context.Context, driverID int64, connectionID string) error {
	ret := _mock.Called(ctx, driverID, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, driverID, connectionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionStore_DeleteConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConnection'
type MockConnectionStore_DeleteConnection_Call struct {
	*mock.Call
}

// DeleteConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - connectionID string
func (_e *MockConnectionStore_Expecter) DeleteConnection(ctx interface{}, driverID interface{}, connectionID interface{}) *MockConnectionStore_DeleteConnection_Call {
	return &MockConnectionStore_DeleteConnection_Call{Call: _e.mock.On("DeleteConnection", ctx, driverID, connectionID)}
}

func (_c *MockConnectionStore_DeleteConnection_Call) Run(run func(ctx context.Context, driverID int64, connectionID string)) *MockConnectionStore_DeleteConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectionStore_DeleteConnection_Call) Return(err error) *MockConnectionStore_DeleteConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionStore_DeleteConnection_Call) RunAndReturn(run func(ctx context.Context, driverID int64, connectionID string) error) *MockConnectionStore_DeleteConnection_Call {
	_c.Call.Return(run)
	return _c
}

// GetDriverIDByConnection provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) GetDriverIDByConnection(ctx context.Context, connectionID string) (*int64, error) {
	ret := _mock.Called(ctx, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for GetDriverIDByConnection")
	}

	var r0 *int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*int64, error)); ok {
		return returnFunc(ctx, connectionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *int64); ok {
		r0 = returnFunc(ctx, connectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, connectionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionStore_GetDriverIDByConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriverIDByConnection'
type MockConnectionStore_GetDriverIDByConnection_Call struct {
	*mock.Call
}

// GetDriverIDByConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID string
func (_e *MockConnectionStore_Expecter) GetDriverIDByConnection(ctx interface{}, connectionID interface{}) *MockConnectionStore_GetDriverIDByConnection_Call {
	return &MockConnectionStore_GetDriverIDByConnection_Call{Call: _e.mock.On("GetDriverIDByConnection", ctx, connectionID)}
}

func (_c *MockConnectionStore_GetDriverIDByConnection_Call) Run(run func(ctx context.Context, connectionID string)) *MockConnectionStore_GetDriverIDByConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionStore_GetDriverIDByConnection_Call) Return(n *int64, err error) *MockConnectionStore_GetDriverIDByConnection_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockConnectionStore_GetDriverIDByConnection_Call) RunAndReturn(run func(ctx context.Context, connectionID string) (*int64, error)) *MockConnectionStore_GetDriverIDByConnection_Call {
	_c.Call.Return(run)
	return _c
}
