// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKMSClient creates a new instance of MockKMSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKMSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKMSClient {
	mock := &MockKMSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKMSClient is an autogenerated mock type for the KMSClient type
type MockKMSClient struct {
	mock.Mock
}

type MockKMSClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKMSClient) EXPECT() *MockKMSClient_Expecter {
	return &MockKMSClient_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) Decrypt(ctx context.Context, keyID string, ciphertext []byte) ([]byte, error) {
	ret := _mock.Called(ctx, keyID, ciphertext)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, keyID, ciphertext)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) []byte); ok {
		r0 = returnFunc(ctx, keyID, ciphertext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, keyID, ciphertext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSClient_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockKMSClient_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - ciphertext []byte
func (_e *MockKMSClient_Expecter) Decrypt(ctx interface{}, keyID interface{}, ciphertext interface{}) *MockKMSClient_Decrypt_Call {
	return &MockKMSClient_Decrypt_Call{Call: _e.mock.On("Decrypt", ctx, keyID, ciphertext)}
}

func (_c *MockKMSClient_Decrypt_Call) Run(run func(ctx context.Context, keyID string, ciphertext []byte)) *MockKMSClient_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKMSClient_Decrypt_Call) Return(bytes []byte, err error) *MockKMSClient_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKMSClient_Decrypt_Call) RunAndReturn(run func(ctx context.Context, keyID string, ciphertext []byte) ([]byte, error)) *MockKMSClient_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateDataKey provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) GenerateDataKey(ctx context.Context, keyID string, keySpec string) ([]byte, []byte, error) {
	ret := _mock.Called(ctx, keyID, keySpec)

	if len(ret) == 0 {
		panic("no return value specified for GenerateDataKey")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, []byte, error)); ok {
		return returnFunc(ctx, keyID, keySpec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = returnFunc(ctx, keyID, keySpec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) []byte); ok {
		r1 = returnFunc(ctx, keyID, keySpec)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, keyID, keySpec)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKMSClient_GenerateDataKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateDataKey'
type MockKMSClient_GenerateDataKey_Call struct {
	*mock.Call
}

// GenerateDataKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - keySpec string
func (_e *MockKMSClient_Expecter) GenerateDataKey(ctx interface{}, keyID interface{}, keySpec interface{}) *MockKMSClient_GenerateDataKey_Call {
	return &MockKMSClient_GenerateDataKey_Call{Call: _e.mock.On("GenerateDataKey", ctx, keyID, keySpec)}
}

func (_c *MockKMSClient_GenerateDataKey_Call) Run(run func(ctx context.Context, keyID string, keySpec string)) *MockKMSClient_GenerateDataKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKMSClient_GenerateDataKey_Call) Return(plaintext []byte, ciphertext []byte, err error) *MockKMSClient_GenerateDataKey_Call {
	_c.Call.Return(plaintext, ciphertext, err)
	return _c
}

func (_c *MockKMSClient_GenerateDataKey_Call) RunAndReturn(run func(ctx context.Context, keyID string, keySpec string) ([]byte, []byte, error)) *MockKMSClient_GenerateDataKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicKey provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) GetPublicKey(ctx context.Context, keyID string) ([]byte, error) {
	ret := _mock.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKey")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, keyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSClient_GetPublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicKey'
type MockKMSClient_GetPublicKey_Call struct {
	*mock.Call
}

// GetPublicKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
func (_e *MockKMSClient_Expecter) GetPublicKey(ctx interface{}, keyID interface{}) *MockKMSClient_GetPublicKey_Call {
	return &MockKMSClient_GetPublicKey_Call{Call: _e.mock.On("GetPublicKey", ctx, keyID)}
}

func (_c *MockKMSClient_GetPublicKey_Call) Run(run func(ctx context.Context, keyID string)) *MockKMSClient_GetPublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKMSClient_GetPublicKey_Call) Return(bytes []byte, err error) *MockKMSClient_GetPublicKey_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKMSClient_GetPublicKey_Call) RunAndReturn(run func(ctx context.Context, keyID string) ([]byte, error)) *MockKMSClient_GetPublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) Sign(ctx context.Context, keyID string, digest []byte) ([]byte, error) {
	ret := _mock.Called(ctx, keyID, digest)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, keyID, digest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) []byte); ok {
		r0 = returnFunc(ctx, keyID, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, keyID, digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSClient_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockKMSClient_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - digest []byte
func (_e *MockKMSClient_Expecter) Sign(ctx interface{}, keyID interface{}, digest interface{}) *MockKMSClient_Sign_Call {
	return &MockKMSClient_Sign_Call{Call: _e.mock.On("Sign", ctx, keyID, digest)}
}

func (_c *MockKMSClient_Sign_Call) Run(run func(ctx context.Context, keyID string, digest []byte)) *MockKMSClient_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKMSClient_Sign_Call) Return(bytes []byte, err error) *MockKMSClient_Sign_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKMSClient_Sign_Call) RunAndReturn(run func(ctx context.Context, keyID string, digest []byte) ([]byte, error)) *MockKMSClient_Sign_Call {
	_c.Call.Return(run)
	return _c
}
