// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/kms"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAWSKMS creates a new instance of MockAWSKMS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAWSKMS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAWSKMS {
	mock := &MockAWSKMS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAWSKMS is an autogenerated mock type for the AWSKMS type
type MockAWSKMS struct {
	mock.Mock
}

type MockAWSKMS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAWSKMS) EXPECT() *MockAWSKMS_Expecter {
	return &MockAWSKMS_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockAWSKMS
func (_mock *MockAWSKMS) Decrypt(ctx context.Context, params *kms.DecryptInput, optFns ...func(*kms.Options)) (*kms.DecryptOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 *kms.DecryptOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.DecryptInput, ...func(*kms.Options)) (*kms.DecryptOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.DecryptInput, ...func(*kms.Options)) *kms.DecryptOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kms.DecryptOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kms.DecryptInput, ...func(*kms.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAWSKMS_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockAWSKMS_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - params *kms.DecryptInput
//   - optFns ...func(*kms.Options)
func (_e *MockAWSKMS_Expecter) Decrypt(ctx interface{}, params interface{}, optFns ...interface{}) *MockAWSKMS_Decrypt_Call {
	return &MockAWSKMS_Decrypt_Call{Call: _e.mock.On("Decrypt",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockAWSKMS_Decrypt_Call) Run(run func(ctx context.Context, params *kms.DecryptInput, optFns ...func(*kms.Options))) *MockAWSKMS_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kms.DecryptInput
		if args[1] != nil {
			arg1 = args[1].(*kms.DecryptInput)
		}
		var arg2 []func(*kms.Options)
		var variadicArgs []func(*kms.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*kms.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAWSKMS_Decrypt_Call) Return(decryptOutput *kms.DecryptOutput, err error) *MockAWSKMS_Decrypt_Call {
	_c.Call.Return(decryptOutput, err)
	return _c
}

func (_c *MockAWSKMS_Decrypt_Call) RunAndReturn(run func(ctx context.Context, params *kms.DecryptInput, optFns ...func(*kms.Options)) (*kms.DecryptOutput, error)) *MockAWSKMS_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateDataKey provides a mock function for the type MockAWSKMS
func (_mock *MockAWSKMS) GenerateDataKey(ctx context.Context, params *kms.GenerateDataKeyInput, optFns ...func(*kms.Options)) (*kms.GenerateDataKeyOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GenerateDataKey")
	}

	var r0 *kms.GenerateDataKeyOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.GenerateDataKeyInput, ...func(*kms.Options)) (*kms.GenerateDataKeyOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.GenerateDataKeyInput, ...func(*kms.Options)) *kms.GenerateDataKeyOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kms.GenerateDataKeyOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kms.GenerateDataKeyInput, ...func(*kms.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAWSKMS_GenerateDataKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateDataKey'
type MockAWSKMS_GenerateDataKey_Call struct {
	*mock.Call
}

// GenerateDataKey is a helper method to define mock.On call
//   - ctx context.Context
//   - params *kms.GenerateDataKeyInput
//   - optFns ...func(*kms.Options)
func (_e *MockAWSKMS_Expecter) GenerateDataKey(ctx interface{}, params interface{}, optFns ...interface{}) *MockAWSKMS_GenerateDataKey_Call {
	return &MockAWSKMS_GenerateDataKey_Call{Call: _e.mock.On("GenerateDataKey",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockAWSKMS_GenerateDataKey_Call) Run(run func(ctx context.Context, params *kms.GenerateDataKeyInput, optFns ...func(*kms.Options))) *MockAWSKMS_GenerateDataKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kms.GenerateDataKeyInput
		if args[1] != nil {
			arg1 = args[1].(*kms.GenerateDataKeyInput)
		}
		var arg2 []func(*kms.Options)
		var variadicArgs []func(*kms.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*kms.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAWSKMS_GenerateDataKey_Call) Return(generateDataKeyOutput *kms.GenerateDataKeyOutput, err error) *MockAWSKMS_GenerateDataKey_Call {
	_c.Call.Return(generateDataKeyOutput, err)
	return _c
}

func (_c *MockAWSKMS_GenerateDataKey_Call) RunAndReturn(run func(ctx context.Context, params *kms.GenerateDataKeyInput, optFns ...func(*kms.Options)) (*kms.GenerateDataKeyOutput, error)) *MockAWSKMS_GenerateDataKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicKey provides a mock function for the type MockAWSKMS
func (_mock *MockAWSKMS) GetPublicKey(ctx context.Context, params *kms.GetPublicKeyInput, optFns ...func(*kms.Options)) (*kms.GetPublicKeyOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKey")
	}

	var r0 *kms.GetPublicKeyOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.GetPublicKeyInput, ...func(*kms.Options)) (*kms.GetPublicKeyOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.GetPublicKeyInput, ...func(*kms.Options)) *kms.GetPublicKeyOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kms.GetPublicKeyOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kms.GetPublicKeyInput, ...func(*kms.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAWSKMS_GetPublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicKey'
type MockAWSKMS_GetPublicKey_Call struct {
	*mock.Call
}

// GetPublicKey is a helper method to define mock.On call
//   - ctx context.Context
//   - params *kms.GetPublicKeyInput
//   - optFns ...func(*kms.Options)
func (_e *MockAWSKMS_Expecter) GetPublicKey(ctx interface{}, params interface{}, optFns ...interface{}) *MockAWSKMS_GetPublicKey_Call {
	return &MockAWSKMS_GetPublicKey_Call{Call: _e.mock.On("GetPublicKey",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockAWSKMS_GetPublicKey_Call) Run(run func(ctx context.Context, params *kms.GetPublicKeyInput, optFns ...func(*kms.Options))) *MockAWSKMS_GetPublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kms.GetPublicKeyInput
		if args[1] != nil {
			arg1 = args[1].(*kms.GetPublicKeyInput)
		}
		var arg2 []func(*kms.Options)
		var variadicArgs []func(*kms.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*kms.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAWSKMS_GetPublicKey_Call) Return(getPublicKeyOutput *kms.GetPublicKeyOutput, err error) *MockAWSKMS_GetPublicKey_Call {
	_c.Call.Return(getPublicKeyOutput, err)
	return _c
}

func (_c *MockAWSKMS_GetPublicKey_Call) RunAndReturn(run func(ctx context.Context, params *kms.GetPublicKeyInput, optFns ...func(*kms.Options)) (*kms.GetPublicKeyOutput, error)) *MockAWSKMS_GetPublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type MockAWSKMS
func (_mock *MockAWSKMS) Sign(ctx context.Context, params *kms.SignInput, optFns ...func(*kms.Options)) (*kms.SignOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 *kms.SignOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.SignInput, ...func(*kms.Options)) (*kms.SignOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.SignInput, ...func(*kms.Options)) *kms.SignOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kms.SignOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kms.SignInput, ...func(*kms.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAWSKMS_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockAWSKMS_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - ctx context.Context
//   - params *kms.SignInput
//   - optFns ...func(*kms.Options)
func (_e *MockAWSKMS_Expecter) Sign(ctx interface{}, params interface{}, optFns ...interface{}) *MockAWSKMS_Sign_Call {
	return &MockAWSKMS_Sign_Call{Call: _e.mock.On("Sign",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockAWSKMS_Sign_Call) Run(run func(ctx context.Context, params *kms.SignInput, optFns ...func(*kms.Options))) *MockAWSKMS_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kms.SignInput
		if args[1] != nil {
			arg1 = args[1].(*kms.SignInput)
		}
		var arg2 []func(*kms.Options)
		var variadicArgs []func(*kms.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*kms.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAWSKMS_Sign_Call) Return(signOutput *kms.SignOutput, err error) *MockAWSKMS_Sign_Call {
	_c.Call.Return(signOutput, err)
	return _c
}

func (_c *MockAWSKMS_Sign_Call) RunAndReturn(run func(ctx context.Context, params *kms.SignInput, optFns ...func(*kms.Options)) (*kms.SignOutput, error)) *MockAWSKMS_Sign_Call {
	_c.Call.Return(run)
	return _c
}
