// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKMSEncryptor creates a new instance of MockKMSEncryptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKMSEncryptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKMSEncryptor {
	mock := &MockKMSEncryptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKMSEncryptor is an autogenerated mock type for the KMSEncryptor type
type MockKMSEncryptor struct {
	mock.Mock
}

type MockKMSEncryptor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKMSEncryptor) EXPECT() *MockKMSEncryptor_Expecter {
	return &MockKMSEncryptor_Expecter{mock: &_m.Mock}
}

// DecryptDataKey provides a mock function for the type MockKMSEncryptor
func (_mock *MockKMSEncryptor) DecryptDataKey(ctx context.Context, ciphertext []byte) ([]byte, error) {
	ret := _mock.Called(ctx, ciphertext)

	if len(ret) == 0 {
		panic("no return value specified for DecryptDataKey")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, ciphertext)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = returnFunc(ctx, ciphertext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, ciphertext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSEncryptor_DecryptDataKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptDataKey'
type MockKMSEncryptor_DecryptDataKey_Call struct {
	*mock.Call
}

// DecryptDataKey is a helper method to define mock.On call
//   - ctx context.Context
//   - ciphertext []byte
func (_e *MockKMSEncryptor_Expecter) DecryptDataKey(ctx interface{}, ciphertext interface{}) *MockKMSEncryptor_DecryptDataKey_Call {
	return &MockKMSEncryptor_DecryptDataKey_Call{Call: _e.mock.On("DecryptDataKey", ctx, ciphertext)}
}

func (_c *MockKMSEncryptor_DecryptDataKey_Call) Run(run func(ctx context.Context, ciphertext []byte)) *MockKMSEncryptor_DecryptDataKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKMSEncryptor_DecryptDataKey_Call) Return(bytes []byte, err error) *MockKMSEncryptor_DecryptDataKey_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKMSEncryptor_DecryptDataKey_Call) RunAndReturn(run func(ctx context.Context, ciphertext []byte) ([]byte, error)) *MockKMSEncryptor_DecryptDataKey_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateDataKey provides a mock function for the type MockKMSEncryptor
func (_mock *MockKMSEncryptor) GenerateDataKey(ctx context.Context) ([]byte, []byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateDataKey")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, []byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) []byte); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKMSEncryptor_GenerateDataKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateDataKey'
type MockKMSEncryptor_GenerateDataKey_Call struct {
	*mock.Call
}

// GenerateDataKey is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKMSEncryptor_Expecter) GenerateDataKey(ctx interface{}) *MockKMSEncryptor_GenerateDataKey_Call {
	return &MockKMSEncryptor_GenerateDataKey_Call{Call: _e.mock.On("GenerateDataKey", ctx)}
}

func (_c *MockKMSEncryptor_GenerateDataKey_Call) Run(run func(ctx context.Context)) *MockKMSEncryptor_GenerateDataKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKMSEncryptor_GenerateDataKey_Call) Return(plaintext []byte, ciphertext []byte, err error) *MockKMSEncryptor_GenerateDataKey_Call {
	_c.Call.Return(plaintext, ciphertext, err)
	return _c
}

func (_c *MockKMSEncryptor_GenerateDataKey_Call) RunAndReturn(run func(ctx context.Context) ([]byte, []byte, error)) *MockKMSEncryptor_GenerateDataKey_Call {
	_c.Call.Return(run)
	return _c
}
