// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package event

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sqs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSQSClient creates a new instance of MockSQSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSQSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSQSClient {
	mock := &MockSQSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSQSClient is an autogenerated mock type for the SQSClient type
type MockSQSClient struct {
	mock.Mock
}

type MockSQSClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSQSClient) EXPECT() *MockSQSClient_Expecter {
	return &MockSQSClient_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function for the type MockSQSClient
func (_mock *MockSQSClient) SendMessage(ctx context.Context, params *sqs.SendMessageInput, optFns ...func(*sqs.Options)) (*sqs.SendMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *sqs.SendMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) (*sqs.SendMessageOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) *sqs.SendMessageOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.SendMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSQSClient_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockSQSClient_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.SendMessageInput
//   - optFns ...func(*sqs.Options)
func (_e *MockSQSClient_Expecter) SendMessage(ctx interface{}, params interface{}, optFns ...interface{}) *MockSQSClient_SendMessage_Call {
	return &MockSQSClient_SendMessage_Call{Call: _e.mock.On("SendMessage",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockSQSClient_SendMessage_Call) Run(run func(ctx context.Context, params *sqs.SendMessageInput, optFns ...func(*sqs.Options))) *MockSQSClient_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.SendMessageInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.SendMessageInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSQSClient_SendMessage_Call) Return(sendMessageOutput *sqs.SendMessageOutput, err error) *MockSQSClient_SendMessage_Call {
	_c.Call.Return(sendMessageOutput, err)
	return _c
}

func (_c *MockSQSClient_SendMessage_Call) RunAndReturn(run func(ctx context.Context, params *sqs.SendMessageInput, optFns ...func(*sqs.Options)) (*sqs.SendMessageOutput, error)) *MockSQSClient_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
