// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/journal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockListJournalEntriesStore creates a new instance of MockListJournalEntriesStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListJournalEntriesStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListJournalEntriesStore {
	mock := &MockListJournalEntriesStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListJournalEntriesStore is an autogenerated mock type for the ListJournalEntriesStore type
type MockListJournalEntriesStore struct {
	mock.Mock
}

type MockListJournalEntriesStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListJournalEntriesStore) EXPECT() *MockListJournalEntriesStore_Expecter {
	return &MockListJournalEntriesStore_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockListJournalEntriesStore
func (_mock *MockListJournalEntriesStore) List(ctx context.Context, input journal.ListInput) ([]journal.Entry, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []journal.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.ListInput) ([]journal.Entry, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.ListInput) []journal.Entry); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]journal.Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, journal.ListInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListJournalEntriesStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockListJournalEntriesStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - input journal.ListInput
func (_e *MockListJournalEntriesStore_Expecter) List(ctx interface{}, input interface{}) *MockListJournalEntriesStore_List_Call {
	return &MockListJournalEntriesStore_List_Call{Call: _e.mock.On("List", ctx, input)}
}

func (_c *MockListJournalEntriesStore_List_Call) Run(run func(ctx context.Context, input journal.ListInput)) *MockListJournalEntriesStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 journal.ListInput
		if args[1] != nil {
			arg1 = args[1].(journal.ListInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListJournalEntriesStore_List_Call) Return(entrys []journal.Entry, err error) *MockListJournalEntriesStore_List_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *MockListJournalEntriesStore_List_Call) RunAndReturn(run func(ctx context.Context, input journal.ListInput) ([]journal.Entry, error)) *MockListJournalEntriesStore_List_Call {
	_c.Call.Return(run)
	return _c
}
