// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDeleteJournalEntryStore creates a new instance of MockDeleteJournalEntryStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteJournalEntryStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteJournalEntryStore {
	mock := &MockDeleteJournalEntryStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeleteJournalEntryStore is an autogenerated mock type for the DeleteJournalEntryStore type
type MockDeleteJournalEntryStore struct {
	mock.Mock
}

type MockDeleteJournalEntryStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteJournalEntryStore) EXPECT() *MockDeleteJournalEntryStore_Expecter {
	return &MockDeleteJournalEntryStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockDeleteJournalEntryStore
func (_mock *MockDeleteJournalEntryStore) Delete(ctx context.Context, driverID int64, raceID int64) error {
	ret := _mock.Called(ctx, driverID, raceID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, driverID, raceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeleteJournalEntryStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeleteJournalEntryStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - raceID int64
func (_e *MockDeleteJournalEntryStore_Expecter) Delete(ctx interface{}, driverID interface{}, raceID interface{}) *MockDeleteJournalEntryStore_Delete_Call {
	return &MockDeleteJournalEntryStore_Delete_Call{Call: _e.mock.On("Delete", ctx, driverID, raceID)}
}

func (_c *MockDeleteJournalEntryStore_Delete_Call) Run(run func(ctx context.Context, driverID int64, raceID int64)) *MockDeleteJournalEntryStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeleteJournalEntryStore_Delete_Call) Return(err error) *MockDeleteJournalEntryStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeleteJournalEntryStore_Delete_Call) RunAndReturn(run func(ctx context.Context, driverID int64, raceID int64) error) *MockDeleteJournalEntryStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}
