// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/journal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJournalServiceForSave creates a new instance of MockJournalServiceForSave. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJournalServiceForSave(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJournalServiceForSave {
	mock := &MockJournalServiceForSave{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJournalServiceForSave is an autogenerated mock type for the JournalServiceForSave type
type MockJournalServiceForSave struct {
	mock.Mock
}

type MockJournalServiceForSave_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJournalServiceForSave) EXPECT() *MockJournalServiceForSave_Expecter {
	return &MockJournalServiceForSave_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type MockJournalServiceForSave
func (_mock *MockJournalServiceForSave) Save(ctx context.Context, input journal.SaveInput) (*journal.Entry, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *journal.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.SaveInput) (*journal.Entry, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.SaveInput) *journal.Entry); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*journal.Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, journal.SaveInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJournalServiceForSave_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockJournalServiceForSave_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - input journal.SaveInput
func (_e *MockJournalServiceForSave_Expecter) Save(ctx interface{}, input interface{}) *MockJournalServiceForSave_Save_Call {
	return &MockJournalServiceForSave_Save_Call{Call: _e.mock.On("Save", ctx, input)}
}

func (_c *MockJournalServiceForSave_Save_Call) Run(run func(ctx context.Context, input journal.SaveInput)) *MockJournalServiceForSave_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 journal.SaveInput
		if args[1] != nil {
			arg1 = args[1].(journal.SaveInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJournalServiceForSave_Save_Call) Return(entry *journal.Entry, err error) *MockJournalServiceForSave_Save_Call {
	_c.Call.Return(entry, err)
	return _c
}

func (_c *MockJournalServiceForSave_Save_Call) RunAndReturn(run func(ctx context.Context, input journal.SaveInput) (*journal.Entry, error)) *MockJournalServiceForSave_Save_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRaceExists provides a mock function for the type MockJournalServiceForSave
func (_mock *MockJournalServiceForSave) ValidateRaceExists(ctx context.Context, driverID int64, raceID int64) (bool, error) {
	ret := _mock.Called(ctx, driverID, raceID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRaceExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return returnFunc(ctx, driverID, raceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = returnFunc(ctx, driverID, raceID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, driverID, raceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJournalServiceForSave_ValidateRaceExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRaceExists'
type MockJournalServiceForSave_ValidateRaceExists_Call struct {
	*mock.Call
}

// ValidateRaceExists is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - raceID int64
func (_e *MockJournalServiceForSave_Expecter) ValidateRaceExists(ctx interface{}, driverID interface{}, raceID interface{}) *MockJournalServiceForSave_ValidateRaceExists_Call {
	return &MockJournalServiceForSave_ValidateRaceExists_Call{Call: _e.mock.On("ValidateRaceExists", ctx, driverID, raceID)}
}

func (_c *MockJournalServiceForSave_ValidateRaceExists_Call) Run(run func(ctx context.Context, driverID int64, raceID int64)) *MockJournalServiceForSave_ValidateRaceExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJournalServiceForSave_ValidateRaceExists_Call) Return(b bool, err error) *MockJournalServiceForSave_ValidateRaceExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockJournalServiceForSave_ValidateRaceExists_Call) RunAndReturn(run func(ctx context.Context, driverID int64, raceID int64) (bool, error)) *MockJournalServiceForSave_ValidateRaceExists_Call {
	_c.Call.Return(run)
	return _c
}
