// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/journal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJournalService creates a new instance of MockJournalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJournalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJournalService {
	mock := &MockJournalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJournalService is an autogenerated mock type for the JournalService type
type MockJournalService struct {
	mock.Mock
}

type MockJournalService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJournalService) EXPECT() *MockJournalService_Expecter {
	return &MockJournalService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockJournalService
func (_mock *MockJournalService) Delete(ctx context.Context, driverID int64, raceID int64) error {
	ret := _mock.Called(ctx, driverID, raceID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, driverID, raceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJournalService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockJournalService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - raceID int64
func (_e *MockJournalService_Expecter) Delete(ctx interface{}, driverID interface{}, raceID interface{}) *MockJournalService_Delete_Call {
	return &MockJournalService_Delete_Call{Call: _e.mock.On("Delete", ctx, driverID, raceID)}
}

func (_c *MockJournalService_Delete_Call) Run(run func(ctx context.Context, driverID int64, raceID int64)) *MockJournalService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJournalService_Delete_Call) Return(err error) *MockJournalService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJournalService_Delete_Call) RunAndReturn(run func(ctx context.Context, driverID int64, raceID int64) error) *MockJournalService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockJournalService
func (_mock *MockJournalService) Get(ctx context.Context, driverID int64, raceID int64) (*journal.Entry, error) {
	ret := _mock.Called(ctx, driverID, raceID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *journal.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*journal.Entry, error)); ok {
		return returnFunc(ctx, driverID, raceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *journal.Entry); ok {
		r0 = returnFunc(ctx, driverID, raceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*journal.Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, driverID, raceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJournalService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockJournalService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - raceID int64
func (_e *MockJournalService_Expecter) Get(ctx interface{}, driverID interface{}, raceID interface{}) *MockJournalService_Get_Call {
	return &MockJournalService_Get_Call{Call: _e.mock.On("Get", ctx, driverID, raceID)}
}

func (_c *MockJournalService_Get_Call) Run(run func(ctx context.Context, driverID int64, raceID int64)) *MockJournalService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJournalService_Get_Call) Return(entry *journal.Entry, err error) *MockJournalService_Get_Call {
	_c.Call.Return(entry, err)
	return _c
}

func (_c *MockJournalService_Get_Call) RunAndReturn(run func(ctx context.Context, driverID int64, raceID int64) (*journal.Entry, error)) *MockJournalService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockJournalService
func (_mock *MockJournalService) List(ctx context.Context, input journal.ListInput) ([]journal.Entry, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []journal.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.ListInput) ([]journal.Entry, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.ListInput) []journal.Entry); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]journal.Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, journal.ListInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJournalService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockJournalService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - input journal.ListInput
func (_e *MockJournalService_Expecter) List(ctx interface{}, input interface{}) *MockJournalService_List_Call {
	return &MockJournalService_List_Call{Call: _e.mock.On("List", ctx, input)}
}

func (_c *MockJournalService_List_Call) Run(run func(ctx context.Context, input journal.ListInput)) *MockJournalService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 journal.ListInput
		if args[1] != nil {
			arg1 = args[1].(journal.ListInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJournalService_List_Call) Return(entrys []journal.Entry, err error) *MockJournalService_List_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *MockJournalService_List_Call) RunAndReturn(run func(ctx context.Context, input journal.ListInput) ([]journal.Entry, error)) *MockJournalService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockJournalService
func (_mock *MockJournalService) Save(ctx context.Context, input journal.SaveInput) (*journal.Entry, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *journal.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.SaveInput) (*journal.Entry, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, journal.SaveInput) *journal.Entry); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*journal.Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, journal.SaveInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJournalService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockJournalService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - input journal.SaveInput
func (_e *MockJournalService_Expecter) Save(ctx interface{}, input interface{}) *MockJournalService_Save_Call {
	return &MockJournalService_Save_Call{Call: _e.mock.On("Save", ctx, input)}
}

func (_c *MockJournalService_Save_Call) Run(run func(ctx context.Context, input journal.SaveInput)) *MockJournalService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 journal.SaveInput
		if args[1] != nil {
			arg1 = args[1].(journal.SaveInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJournalService_Save_Call) Return(entry *journal.Entry, err error) *MockJournalService_Save_Call {
	_c.Call.Return(entry, err)
	return _c
}

func (_c *MockJournalService_Save_Call) RunAndReturn(run func(ctx context.Context, input journal.SaveInput) (*journal.Entry, error)) *MockJournalService_Save_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRaceExists provides a mock function for the type MockJournalService
func (_mock *MockJournalService) ValidateRaceExists(ctx context.Context, driverID int64, raceID int64) (bool, error) {
	ret := _mock.Called(ctx, driverID, raceID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRaceExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return returnFunc(ctx, driverID, raceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = returnFunc(ctx, driverID, raceID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, driverID, raceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJournalService_ValidateRaceExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRaceExists'
type MockJournalService_ValidateRaceExists_Call struct {
	*mock.Call
}

// ValidateRaceExists is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - raceID int64
func (_e *MockJournalService_Expecter) ValidateRaceExists(ctx interface{}, driverID interface{}, raceID interface{}) *MockJournalService_ValidateRaceExists_Call {
	return &MockJournalService_ValidateRaceExists_Call{Call: _e.mock.On("ValidateRaceExists", ctx, driverID, raceID)}
}

func (_c *MockJournalService_ValidateRaceExists_Call) Run(run func(ctx context.Context, driverID int64, raceID int64)) *MockJournalService_ValidateRaceExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJournalService_ValidateRaceExists_Call) Return(b bool, err error) *MockJournalService_ValidateRaceExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockJournalService_ValidateRaceExists_Call) RunAndReturn(run func(ctx context.Context, driverID int64, raceID int64) (bool, error)) *MockJournalService_ValidateRaceExists_Call {
	_c.Call.Return(run)
	return _c
}
