// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/journal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetJournalEntryStore creates a new instance of MockGetJournalEntryStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetJournalEntryStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetJournalEntryStore {
	mock := &MockGetJournalEntryStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetJournalEntryStore is an autogenerated mock type for the GetJournalEntryStore type
type MockGetJournalEntryStore struct {
	mock.Mock
}

type MockGetJournalEntryStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetJournalEntryStore) EXPECT() *MockGetJournalEntryStore_Expecter {
	return &MockGetJournalEntryStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockGetJournalEntryStore
func (_mock *MockGetJournalEntryStore) Get(ctx context.Context, driverID int64, raceID int64) (*journal.Entry, error) {
	ret := _mock.Called(ctx, driverID, raceID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *journal.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*journal.Entry, error)); ok {
		return returnFunc(ctx, driverID, raceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *journal.Entry); ok {
		r0 = returnFunc(ctx, driverID, raceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*journal.Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, driverID, raceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetJournalEntryStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGetJournalEntryStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - raceID int64
func (_e *MockGetJournalEntryStore_Expecter) Get(ctx interface{}, driverID interface{}, raceID interface{}) *MockGetJournalEntryStore_Get_Call {
	return &MockGetJournalEntryStore_Get_Call{Call: _e.mock.On("Get", ctx, driverID, raceID)}
}

func (_c *MockGetJournalEntryStore_Get_Call) Run(run func(ctx context.Context, driverID int64, raceID int64)) *MockGetJournalEntryStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGetJournalEntryStore_Get_Call) Return(entry *journal.Entry, err error) *MockGetJournalEntryStore_Get_Call {
	_c.Call.Return(entry, err)
	return _c
}

func (_c *MockGetJournalEntryStore_Get_Call) RunAndReturn(run func(ctx context.Context, driverID int64, raceID int64) (*journal.Entry, error)) *MockGetJournalEntryStore_Get_Call {
	_c.Call.Return(run)
	return _c
}
