// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDeleteRacesStore creates a new instance of MockDeleteRacesStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteRacesStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteRacesStore {
	mock := &MockDeleteRacesStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeleteRacesStore is an autogenerated mock type for the DeleteRacesStore type
type MockDeleteRacesStore struct {
	mock.Mock
}

type MockDeleteRacesStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteRacesStore) EXPECT() *MockDeleteRacesStore_Expecter {
	return &MockDeleteRacesStore_Expecter{mock: &_m.Mock}
}

// DeleteDriverRaces provides a mock function for the type MockDeleteRacesStore
func (_mock *MockDeleteRacesStore) DeleteDriverRaces(ctx context.Context, driverID int64) error {
	ret := _mock.Called(ctx, driverID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDriverRaces")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, driverID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeleteRacesStore_DeleteDriverRaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDriverRaces'
type MockDeleteRacesStore_DeleteDriverRaces_Call struct {
	*mock.Call
}

// DeleteDriverRaces is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
func (_e *MockDeleteRacesStore_Expecter) DeleteDriverRaces(ctx interface{}, driverID interface{}) *MockDeleteRacesStore_DeleteDriverRaces_Call {
	return &MockDeleteRacesStore_DeleteDriverRaces_Call{Call: _e.mock.On("DeleteDriverRaces", ctx, driverID)}
}

func (_c *MockDeleteRacesStore_DeleteDriverRaces_Call) Run(run func(ctx context.Context, driverID int64)) *MockDeleteRacesStore_DeleteDriverRaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeleteRacesStore_DeleteDriverRaces_Call) Return(err error) *MockDeleteRacesStore_DeleteDriverRaces_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeleteRacesStore_DeleteDriverRaces_Call) RunAndReturn(run func(ctx context.Context, driverID int64) error) *MockDeleteRacesStore_DeleteDriverRaces_Call {
	_c.Call.Return(run)
	return _c
}
