// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"
	"time"

	"github.com/jonsabados/saturdaysspinout/analytics"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalyticsService creates a new instance of MockAnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsService {
	mock := &MockAnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalyticsService is an autogenerated mock type for the AnalyticsService type
type MockAnalyticsService struct {
	mock.Mock
}

type MockAnalyticsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsService) EXPECT() *MockAnalyticsService_Expecter {
	return &MockAnalyticsService_Expecter{mock: &_m.Mock}
}

// GetAnalytics provides a mock function for the type MockAnalyticsService
func (_mock *MockAnalyticsService) GetAnalytics(ctx context.Context, req analytics.AnalyticsRequest) (*analytics.AnalyticsResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalytics")
	}

	var r0 *analytics.AnalyticsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, analytics.AnalyticsRequest) (*analytics.AnalyticsResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, analytics.AnalyticsRequest) *analytics.AnalyticsResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*analytics.AnalyticsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, analytics.AnalyticsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsService_GetAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnalytics'
type MockAnalyticsService_GetAnalytics_Call struct {
	*mock.Call
}

// GetAnalytics is a helper method to define mock.On call
//   - ctx context.Context
//   - req analytics.AnalyticsRequest
func (_e *MockAnalyticsService_Expecter) GetAnalytics(ctx interface{}, req interface{}) *MockAnalyticsService_GetAnalytics_Call {
	return &MockAnalyticsService_GetAnalytics_Call{Call: _e.mock.On("GetAnalytics", ctx, req)}
}

func (_c *MockAnalyticsService_GetAnalytics_Call) Run(run func(ctx context.Context, req analytics.AnalyticsRequest)) *MockAnalyticsService_GetAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 analytics.AnalyticsRequest
		if args[1] != nil {
			arg1 = args[1].(analytics.AnalyticsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsService_GetAnalytics_Call) Return(analyticsResult *analytics.AnalyticsResult, err error) *MockAnalyticsService_GetAnalytics_Call {
	_c.Call.Return(analyticsResult, err)
	return _c
}

func (_c *MockAnalyticsService_GetAnalytics_Call) RunAndReturn(run func(ctx context.Context, req analytics.AnalyticsRequest) (*analytics.AnalyticsResult, error)) *MockAnalyticsService_GetAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// GetDimensions provides a mock function for the type MockAnalyticsService
func (_mock *MockAnalyticsService) GetDimensions(ctx context.Context, driverID int64, from time.Time, to time.Time) (*analytics.Dimensions, error) {
	ret := _mock.Called(ctx, driverID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetDimensions")
	}

	var r0 *analytics.Dimensions
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) (*analytics.Dimensions, error)); ok {
		return returnFunc(ctx, driverID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) *analytics.Dimensions); ok {
		r0 = returnFunc(ctx, driverID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*analytics.Dimensions)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, driverID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsService_GetDimensions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDimensions'
type MockAnalyticsService_GetDimensions_Call struct {
	*mock.Call
}

// GetDimensions is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - from time.Time
//   - to time.Time
func (_e *MockAnalyticsService_Expecter) GetDimensions(ctx interface{}, driverID interface{}, from interface{}, to interface{}) *MockAnalyticsService_GetDimensions_Call {
	return &MockAnalyticsService_GetDimensions_Call{Call: _e.mock.On("GetDimensions", ctx, driverID, from, to)}
}

func (_c *MockAnalyticsService_GetDimensions_Call) Run(run func(ctx context.Context, driverID int64, from time.Time, to time.Time)) *MockAnalyticsService_GetDimensions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAnalyticsService_GetDimensions_Call) Return(dimensions *analytics.Dimensions, err error) *MockAnalyticsService_GetDimensions_Call {
	_c.Call.Return(dimensions, err)
	return _c
}

func (_c *MockAnalyticsService_GetDimensions_Call) RunAndReturn(run func(ctx context.Context, driverID int64, from time.Time, to time.Time) (*analytics.Dimensions, error)) *MockAnalyticsService_GetDimensions_Call {
	_c.Call.Return(run)
	return _c
}
