// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"
	"time"

	"github.com/jonsabados/saturdaysspinout/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetRacesStore creates a new instance of MockGetRacesStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetRacesStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetRacesStore {
	mock := &MockGetRacesStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetRacesStore is an autogenerated mock type for the GetRacesStore type
type MockGetRacesStore struct {
	mock.Mock
}

type MockGetRacesStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetRacesStore) EXPECT() *MockGetRacesStore_Expecter {
	return &MockGetRacesStore_Expecter{mock: &_m.Mock}
}

// GetDriverSessions provides a mock function for the type MockGetRacesStore
func (_mock *MockGetRacesStore) GetDriverSessions(ctx context.Context, driverID int64, from time.Time, to time.Time) ([]store.DriverSession, error) {
	ret := _mock.Called(ctx, driverID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetDriverSessions")
	}

	var r0 []store.DriverSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) ([]store.DriverSession, error)); ok {
		return returnFunc(ctx, driverID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) []store.DriverSession); ok {
		r0 = returnFunc(ctx, driverID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.DriverSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, driverID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetRacesStore_GetDriverSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriverSessions'
type MockGetRacesStore_GetDriverSessions_Call struct {
	*mock.Call
}

// GetDriverSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - from time.Time
//   - to time.Time
func (_e *MockGetRacesStore_Expecter) GetDriverSessions(ctx interface{}, driverID interface{}, from interface{}, to interface{}) *MockGetRacesStore_GetDriverSessions_Call {
	return &MockGetRacesStore_GetDriverSessions_Call{Call: _e.mock.On("GetDriverSessions", ctx, driverID, from, to)}
}

func (_c *MockGetRacesStore_GetDriverSessions_Call) Run(run func(ctx context.Context, driverID int64, from time.Time, to time.Time)) *MockGetRacesStore_GetDriverSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGetRacesStore_GetDriverSessions_Call) Return(driverSessions []store.DriverSession, err error) *MockGetRacesStore_GetDriverSessions_Call {
	_c.Call.Return(driverSessions, err)
	return _c
}

func (_c *MockGetRacesStore_GetDriverSessions_Call) RunAndReturn(run func(ctx context.Context, driverID int64, from time.Time, to time.Time) ([]store.DriverSession, error)) *MockGetRacesStore_GetDriverSessions_Call {
	_c.Call.Return(run)
	return _c
}
