// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"
	"time"

	"github.com/jonsabados/saturdaysspinout/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetRaceStore creates a new instance of MockGetRaceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetRaceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetRaceStore {
	mock := &MockGetRaceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetRaceStore is an autogenerated mock type for the GetRaceStore type
type MockGetRaceStore struct {
	mock.Mock
}

type MockGetRaceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetRaceStore) EXPECT() *MockGetRaceStore_Expecter {
	return &MockGetRaceStore_Expecter{mock: &_m.Mock}
}

// GetDriverSession provides a mock function for the type MockGetRaceStore
func (_mock *MockGetRaceStore) GetDriverSession(ctx context.Context, driverID int64, startTime time.Time) (*store.DriverSession, error) {
	ret := _mock.Called(ctx, driverID, startTime)

	if len(ret) == 0 {
		panic("no return value specified for GetDriverSession")
	}

	var r0 *store.DriverSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time) (*store.DriverSession, error)); ok {
		return returnFunc(ctx, driverID, startTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time) *store.DriverSession); ok {
		r0 = returnFunc(ctx, driverID, startTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.DriverSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time) error); ok {
		r1 = returnFunc(ctx, driverID, startTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetRaceStore_GetDriverSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriverSession'
type MockGetRaceStore_GetDriverSession_Call struct {
	*mock.Call
}

// GetDriverSession is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - startTime time.Time
func (_e *MockGetRaceStore_Expecter) GetDriverSession(ctx interface{}, driverID interface{}, startTime interface{}) *MockGetRaceStore_GetDriverSession_Call {
	return &MockGetRaceStore_GetDriverSession_Call{Call: _e.mock.On("GetDriverSession", ctx, driverID, startTime)}
}

func (_c *MockGetRaceStore_GetDriverSession_Call) Run(run func(ctx context.Context, driverID int64, startTime time.Time)) *MockGetRaceStore_GetDriverSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGetRaceStore_GetDriverSession_Call) Return(driverSession *store.DriverSession, err error) *MockGetRaceStore_GetDriverSession_Call {
	_c.Call.Return(driverSession, err)
	return _c
}

func (_c *MockGetRaceStore_GetDriverSession_Call) RunAndReturn(run func(ctx context.Context, driverID int64, startTime time.Time) (*store.DriverSession, error)) *MockGetRaceStore_GetDriverSession_Call {
	_c.Call.Return(run)
	return _c
}
