// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package driver

import (
	"context"
	"time"

	"github.com/jonsabados/saturdaysspinout/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// GetDriver provides a mock function for the type MockStore
func (_mock *MockStore) GetDriver(ctx context.Context, driverID int64) (*store.Driver, error) {
	ret := _mock.Called(ctx, driverID)

	if len(ret) == 0 {
		panic("no return value specified for GetDriver")
	}

	var r0 *store.Driver
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*store.Driver, error)); ok {
		return returnFunc(ctx, driverID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *store.Driver); ok {
		r0 = returnFunc(ctx, driverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Driver)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, driverID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriver'
type MockStore_GetDriver_Call struct {
	*mock.Call
}

// GetDriver is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
func (_e *MockStore_Expecter) GetDriver(ctx interface{}, driverID interface{}) *MockStore_GetDriver_Call {
	return &MockStore_GetDriver_Call{Call: _e.mock.On("GetDriver", ctx, driverID)}
}

func (_c *MockStore_GetDriver_Call) Run(run func(ctx context.Context, driverID int64)) *MockStore_GetDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetDriver_Call) Return(driver *store.Driver, err error) *MockStore_GetDriver_Call {
	_c.Call.Return(driver, err)
	return _c
}

func (_c *MockStore_GetDriver_Call) RunAndReturn(run func(ctx context.Context, driverID int64) (*store.Driver, error)) *MockStore_GetDriver_Call {
	_c.Call.Return(run)
	return _c
}

// GetDriverSession provides a mock function for the type MockStore
func (_mock *MockStore) GetDriverSession(ctx context.Context, driverID int64, startTime time.Time) (*store.DriverSession, error) {
	ret := _mock.Called(ctx, driverID, startTime)

	if len(ret) == 0 {
		panic("no return value specified for GetDriverSession")
	}

	var r0 *store.DriverSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time) (*store.DriverSession, error)); ok {
		return returnFunc(ctx, driverID, startTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time) *store.DriverSession); ok {
		r0 = returnFunc(ctx, driverID, startTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.DriverSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time) error); ok {
		r1 = returnFunc(ctx, driverID, startTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetDriverSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriverSession'
type MockStore_GetDriverSession_Call struct {
	*mock.Call
}

// GetDriverSession is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - startTime time.Time
func (_e *MockStore_Expecter) GetDriverSession(ctx interface{}, driverID interface{}, startTime interface{}) *MockStore_GetDriverSession_Call {
	return &MockStore_GetDriverSession_Call{Call: _e.mock.On("GetDriverSession", ctx, driverID, startTime)}
}

func (_c *MockStore_GetDriverSession_Call) Run(run func(ctx context.Context, driverID int64, startTime time.Time)) *MockStore_GetDriverSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetDriverSession_Call) Return(driverSession *store.DriverSession, err error) *MockStore_GetDriverSession_Call {
	_c.Call.Return(driverSession, err)
	return _c
}

func (_c *MockStore_GetDriverSession_Call) RunAndReturn(run func(ctx context.Context, driverID int64, startTime time.Time) (*store.DriverSession, error)) *MockStore_GetDriverSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetDriverSessions provides a mock function for the type MockStore
func (_mock *MockStore) GetDriverSessions(ctx context.Context, driverID int64, from time.Time, to time.Time) ([]store.DriverSession, error) {
	ret := _mock.Called(ctx, driverID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetDriverSessions")
	}

	var r0 []store.DriverSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) ([]store.DriverSession, error)); ok {
		return returnFunc(ctx, driverID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) []store.DriverSession); ok {
		r0 = returnFunc(ctx, driverID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.DriverSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, driverID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetDriverSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriverSessions'
type MockStore_GetDriverSessions_Call struct {
	*mock.Call
}

// GetDriverSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - from time.Time
//   - to time.Time
func (_e *MockStore_Expecter) GetDriverSessions(ctx interface{}, driverID interface{}, from interface{}, to interface{}) *MockStore_GetDriverSessions_Call {
	return &MockStore_GetDriverSessions_Call{Call: _e.mock.On("GetDriverSessions", ctx, driverID, from, to)}
}

func (_c *MockStore_GetDriverSessions_Call) Run(run func(ctx context.Context, driverID int64, from time.Time, to time.Time)) *MockStore_GetDriverSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_GetDriverSessions_Call) Return(driverSessions []store.DriverSession, err error) *MockStore_GetDriverSessions_Call {
	_c.Call.Return(driverSessions, err)
	return _c
}

func (_c *MockStore_GetDriverSessions_Call) RunAndReturn(run func(ctx context.Context, driverID int64, from time.Time, to time.Time) ([]store.DriverSession, error)) *MockStore_GetDriverSessions_Call {
	_c.Call.Return(run)
	return _c
}
