// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package series

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/series"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSeriesService creates a new instance of MockSeriesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeriesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeriesService {
	mock := &MockSeriesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSeriesService is an autogenerated mock type for the SeriesService type
type MockSeriesService struct {
	mock.Mock
}

type MockSeriesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeriesService) EXPECT() *MockSeriesService_Expecter {
	return &MockSeriesService_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockSeriesService
func (_mock *MockSeriesService) GetAll(ctx context.Context, accessToken string) ([]series.Series, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []series.Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]series.Series, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []series.Series); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]series.Series)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeriesService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockSeriesService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockSeriesService_Expecter) GetAll(ctx interface{}, accessToken interface{}) *MockSeriesService_GetAll_Call {
	return &MockSeriesService_GetAll_Call{Call: _e.mock.On("GetAll", ctx, accessToken)}
}

func (_c *MockSeriesService_GetAll_Call) Run(run func(ctx context.Context, accessToken string)) *MockSeriesService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeriesService_GetAll_Call) Return(seriess []series.Series, err error) *MockSeriesService_GetAll_Call {
	_c.Call.Return(seriess, err)
	return _c
}

func (_c *MockSeriesService_GetAll_Call) RunAndReturn(run func(ctx context.Context, accessToken string) ([]series.Series, error)) *MockSeriesService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
