// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// HandleCallback provides a mock function for the type MockService
func (_mock *MockService) HandleCallback(ctx context.Context, code string, codeVerifier string, redirectURI string) (*auth.Result, error) {
	ret := _mock.Called(ctx, code, codeVerifier, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for HandleCallback")
	}

	var r0 *auth.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*auth.Result, error)); ok {
		return returnFunc(ctx, code, codeVerifier, redirectURI)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *auth.Result); ok {
		r0 = returnFunc(ctx, code, codeVerifier, redirectURI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, code, codeVerifier, redirectURI)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_HandleCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCallback'
type MockService_HandleCallback_Call struct {
	*mock.Call
}

// HandleCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - codeVerifier string
//   - redirectURI string
func (_e *MockService_Expecter) HandleCallback(ctx interface{}, code interface{}, codeVerifier interface{}, redirectURI interface{}) *MockService_HandleCallback_Call {
	return &MockService_HandleCallback_Call{Call: _e.mock.On("HandleCallback", ctx, code, codeVerifier, redirectURI)}
}

func (_c *MockService_HandleCallback_Call) Run(run func(ctx context.Context, code string, codeVerifier string, redirectURI string)) *MockService_HandleCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_HandleCallback_Call) Return(result *auth.Result, err error) *MockService_HandleCallback_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockService_HandleCallback_Call) RunAndReturn(run func(ctx context.Context, code string, codeVerifier string, redirectURI string) (*auth.Result, error)) *MockService_HandleCallback_Call {
	_c.Call.Return(run)
	return _c
}

// HandleRefresh provides a mock function for the type MockService
func (_mock *MockService) HandleRefresh(ctx context.Context, userID int64, userName string, refreshToken string) (*auth.Result, error) {
	ret := _mock.Called(ctx, userID, userName, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for HandleRefresh")
	}

	var r0 *auth.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) (*auth.Result, error)); ok {
		return returnFunc(ctx, userID, userName, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) *auth.Result); ok {
		r0 = returnFunc(ctx, userID, userName, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = returnFunc(ctx, userID, userName, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_HandleRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRefresh'
type MockService_HandleRefresh_Call struct {
	*mock.Call
}

// HandleRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - userName string
//   - refreshToken string
func (_e *MockService_Expecter) HandleRefresh(ctx interface{}, userID interface{}, userName interface{}, refreshToken interface{}) *MockService_HandleRefresh_Call {
	return &MockService_HandleRefresh_Call{Call: _e.mock.On("HandleRefresh", ctx, userID, userName, refreshToken)}
}

func (_c *MockService_HandleRefresh_Call) Run(run func(ctx context.Context, userID int64, userName string, refreshToken string)) *MockService_HandleRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_HandleRefresh_Call) Return(result *auth.Result, err error) *MockService_HandleRefresh_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockService_HandleRefresh_Call) RunAndReturn(run func(ctx context.Context, userID int64, userName string, refreshToken string) (*auth.Result, error)) *MockService_HandleRefresh_Call {
	_c.Call.Return(run)
	return _c
}
