// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/ingestion"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProcessor creates a new instance of MockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessor {
	mock := &MockProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessor is an autogenerated mock type for the Processor type
type MockProcessor struct {
	mock.Mock
}

type MockProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessor) EXPECT() *MockProcessor_Expecter {
	return &MockProcessor_Expecter{mock: &_m.Mock}
}

// IngestRaces provides a mock function for the type MockProcessor
func (_mock *MockProcessor) IngestRaces(ctx context.Context, request ingestion.RaceIngestionRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for IngestRaces")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingestion.RaceIngestionRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcessor_IngestRaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestRaces'
type MockProcessor_IngestRaces_Call struct {
	*mock.Call
}

// IngestRaces is a helper method to define mock.On call
//   - ctx context.Context
//   - request ingestion.RaceIngestionRequest
func (_e *MockProcessor_Expecter) IngestRaces(ctx interface{}, request interface{}) *MockProcessor_IngestRaces_Call {
	return &MockProcessor_IngestRaces_Call{Call: _e.mock.On("IngestRaces", ctx, request)}
}

func (_c *MockProcessor_IngestRaces_Call) Run(run func(ctx context.Context, request ingestion.RaceIngestionRequest)) *MockProcessor_IngestRaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ingestion.RaceIngestionRequest
		if args[1] != nil {
			arg1 = args[1].(ingestion.RaceIngestionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProcessor_IngestRaces_Call) Return(err error) *MockProcessor_IngestRaces_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcessor_IngestRaces_Call) RunAndReturn(run func(ctx context.Context, request ingestion.RaceIngestionRequest) error) *MockProcessor_IngestRaces_Call {
	_c.Call.Return(run)
	return _c
}
