// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionStore creates a new instance of MockConnectionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionStore {
	mock := &MockConnectionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionStore is an autogenerated mock type for the ConnectionStore type
type MockConnectionStore struct {
	mock.Mock
}

type MockConnectionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionStore) EXPECT() *MockConnectionStore_Expecter {
	return &MockConnectionStore_Expecter{mock: &_m.Mock}
}

// SaveConnection provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) SaveConnection(ctx context.Context, conn store.WebSocketConnection) error {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for SaveConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.WebSocketConnection) error); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionStore_SaveConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveConnection'
type MockConnectionStore_SaveConnection_Call struct {
	*mock.Call
}

// SaveConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - conn store.WebSocketConnection
func (_e *MockConnectionStore_Expecter) SaveConnection(ctx interface{}, conn interface{}) *MockConnectionStore_SaveConnection_Call {
	return &MockConnectionStore_SaveConnection_Call{Call: _e.mock.On("SaveConnection", ctx, conn)}
}

func (_c *MockConnectionStore_SaveConnection_Call) Run(run func(ctx context.Context, conn store.WebSocketConnection)) *MockConnectionStore_SaveConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.WebSocketConnection
		if args[1] != nil {
			arg1 = args[1].(store.WebSocketConnection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionStore_SaveConnection_Call) Return(err error) *MockConnectionStore_SaveConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionStore_SaveConnection_Call) RunAndReturn(run func(ctx context.Context, conn store.WebSocketConnection) error) *MockConnectionStore_SaveConnection_Call {
	_c.Call.Return(run)
	return _c
}
