// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cars

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/iracing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIRacingClient creates a new instance of MockIRacingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRacingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRacingClient {
	mock := &MockIRacingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRacingClient is an autogenerated mock type for the IRacingClient type
type MockIRacingClient struct {
	mock.Mock
}

type MockIRacingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRacingClient) EXPECT() *MockIRacingClient_Expecter {
	return &MockIRacingClient_Expecter{mock: &_m.Mock}
}

// GetCarAssets provides a mock function for the type MockIRacingClient
func (_mock *MockIRacingClient) GetCarAssets(ctx context.Context, accessToken string) (map[int64]iracing.CarAssets, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetCarAssets")
	}

	var r0 map[int64]iracing.CarAssets
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[int64]iracing.CarAssets, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[int64]iracing.CarAssets); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]iracing.CarAssets)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRacingClient_GetCarAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCarAssets'
type MockIRacingClient_GetCarAssets_Call struct {
	*mock.Call
}

// GetCarAssets is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockIRacingClient_Expecter) GetCarAssets(ctx interface{}, accessToken interface{}) *MockIRacingClient_GetCarAssets_Call {
	return &MockIRacingClient_GetCarAssets_Call{Call: _e.mock.On("GetCarAssets", ctx, accessToken)}
}

func (_c *MockIRacingClient_GetCarAssets_Call) Run(run func(ctx context.Context, accessToken string)) *MockIRacingClient_GetCarAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRacingClient_GetCarAssets_Call) Return(int64ToCarAssets map[int64]iracing.CarAssets, err error) *MockIRacingClient_GetCarAssets_Call {
	_c.Call.Return(int64ToCarAssets, err)
	return _c
}

func (_c *MockIRacingClient_GetCarAssets_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (map[int64]iracing.CarAssets, error)) *MockIRacingClient_GetCarAssets_Call {
	_c.Call.Return(run)
	return _c
}

// GetCars provides a mock function for the type MockIRacingClient
func (_mock *MockIRacingClient) GetCars(ctx context.Context, accessToken string) ([]iracing.CarInfo, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetCars")
	}

	var r0 []iracing.CarInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]iracing.CarInfo, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []iracing.CarInfo); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iracing.CarInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRacingClient_GetCars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCars'
type MockIRacingClient_GetCars_Call struct {
	*mock.Call
}

// GetCars is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockIRacingClient_Expecter) GetCars(ctx interface{}, accessToken interface{}) *MockIRacingClient_GetCars_Call {
	return &MockIRacingClient_GetCars_Call{Call: _e.mock.On("GetCars", ctx, accessToken)}
}

func (_c *MockIRacingClient_GetCars_Call) Run(run func(ctx context.Context, accessToken string)) *MockIRacingClient_GetCars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRacingClient_GetCars_Call) Return(carInfos []iracing.CarInfo, err error) *MockIRacingClient_GetCars_Call {
	_c.Call.Return(carInfos, err)
	return _c
}

func (_c *MockIRacingClient_GetCars_Call) RunAndReturn(run func(ctx context.Context, accessToken string) ([]iracing.CarInfo, error)) *MockIRacingClient_GetCars_Call {
	_c.Call.Return(run)
	return _c
}
