// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tracks

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/tracks"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTracksService creates a new instance of MockTracksService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTracksService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTracksService {
	mock := &MockTracksService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTracksService is an autogenerated mock type for the TracksService type
type MockTracksService struct {
	mock.Mock
}

type MockTracksService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTracksService) EXPECT() *MockTracksService_Expecter {
	return &MockTracksService_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockTracksService
func (_mock *MockTracksService) GetAll(ctx context.Context, accessToken string) ([]tracks.Track, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []tracks.Track
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]tracks.Track, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []tracks.Track); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tracks.Track)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTracksService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTracksService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockTracksService_Expecter) GetAll(ctx interface{}, accessToken interface{}) *MockTracksService_GetAll_Call {
	return &MockTracksService_GetAll_Call{Call: _e.mock.On("GetAll", ctx, accessToken)}
}

func (_c *MockTracksService_GetAll_Call) Run(run func(ctx context.Context, accessToken string)) *MockTracksService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTracksService_GetAll_Call) Return(tracks1 []tracks.Track, err error) *MockTracksService_GetAll_Call {
	_c.Call.Return(tracks1, err)
	return _c
}

func (_c *MockTracksService_GetAll_Call) RunAndReturn(run func(ctx context.Context, accessToken string) ([]tracks.Track, error)) *MockTracksService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
