// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ping

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPusher creates a new instance of MockPusher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPusher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPusher {
	mock := &MockPusher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPusher is an autogenerated mock type for the Pusher type
type MockPusher struct {
	mock.Mock
}

type MockPusher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPusher) EXPECT() *MockPusher_Expecter {
	return &MockPusher_Expecter{mock: &_m.Mock}
}

// Disconnect provides a mock function for the type MockPusher
func (_mock *MockPusher) Disconnect(ctx context.Context, driverID int64, connectionID string) {
	_mock.Called(ctx, driverID, connectionID)
	return
}

// MockPusher_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockPusher_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - connectionID string
func (_e *MockPusher_Expecter) Disconnect(ctx interface{}, driverID interface{}, connectionID interface{}) *MockPusher_Disconnect_Call {
	return &MockPusher_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx, driverID, connectionID)}
}

func (_c *MockPusher_Disconnect_Call) Run(run func(ctx context.Context, driverID int64, connectionID string)) *MockPusher_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPusher_Disconnect_Call) Return() *MockPusher_Disconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPusher_Disconnect_Call) RunAndReturn(run func(ctx context.Context, driverID int64, connectionID string)) *MockPusher_Disconnect_Call {
	_c.Run(run)
	return _c
}

// Push provides a mock function for the type MockPusher
func (_mock *MockPusher) Push(ctx context.Context, driverID int64, connectionID string, actionType string, payload any) error {
	ret := _mock.Called(ctx, driverID, connectionID, actionType, payload)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, any) error); ok {
		r0 = returnFunc(ctx, driverID, connectionID, actionType, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPusher_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockPusher_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - connectionID string
//   - actionType string
//   - payload any
func (_e *MockPusher_Expecter) Push(ctx interface{}, driverID interface{}, connectionID interface{}, actionType interface{}, payload interface{}) *MockPusher_Push_Call {
	return &MockPusher_Push_Call{Call: _e.mock.On("Push", ctx, driverID, connectionID, actionType, payload)}
}

func (_c *MockPusher_Push_Call) Run(run func(ctx context.Context, driverID int64, connectionID string, actionType string, payload any)) *MockPusher_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPusher_Push_Call) Return(err error) *MockPusher_Push_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPusher_Push_Call) RunAndReturn(run func(ctx context.Context, driverID int64, connectionID string, actionType string, payload any) error) *MockPusher_Push_Call {
	_c.Call.Return(run)
	return _c
}
