// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ping

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionStore creates a new instance of MockConnectionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionStore {
	mock := &MockConnectionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionStore is an autogenerated mock type for the ConnectionStore type
type MockConnectionStore struct {
	mock.Mock
}

type MockConnectionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionStore) EXPECT() *MockConnectionStore_Expecter {
	return &MockConnectionStore_Expecter{mock: &_m.Mock}
}

// GetConnection provides a mock function for the type MockConnectionStore
func (_mock *MockConnectionStore) GetConnection(ctx context.Context, driverID int64, connectionID string) (*store.WebSocketConnection, error) {
	ret := _mock.Called(ctx, driverID, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for GetConnection")
	}

	var r0 *store.WebSocketConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (*store.WebSocketConnection, error)); ok {
		return returnFunc(ctx, driverID, connectionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) *store.WebSocketConnection); ok {
		r0 = returnFunc(ctx, driverID, connectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.WebSocketConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, driverID, connectionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionStore_GetConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnection'
type MockConnectionStore_GetConnection_Call struct {
	*mock.Call
}

// GetConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - connectionID string
func (_e *MockConnectionStore_Expecter) GetConnection(ctx interface{}, driverID interface{}, connectionID interface{}) *MockConnectionStore_GetConnection_Call {
	return &MockConnectionStore_GetConnection_Call{Call: _e.mock.On("GetConnection", ctx, driverID, connectionID)}
}

func (_c *MockConnectionStore_GetConnection_Call) Run(run func(ctx context.Context, driverID int64, connectionID string)) *MockConnectionStore_GetConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectionStore_GetConnection_Call) Return(webSocketConnection *store.WebSocketConnection, err error) *MockConnectionStore_GetConnection_Call {
	_c.Call.Return(webSocketConnection, err)
	return _c
}

func (_c *MockConnectionStore_GetConnection_Call) RunAndReturn(run func(ctx context.Context, driverID int64, connectionID string) (*store.WebSocketConnection, error)) *MockConnectionStore_GetConnection_Call {
	_c.Call.Return(run)
	return _c
}
