// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package journal

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricsEmitter creates a new instance of MockMetricsEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsEmitter {
	mock := &MockMetricsEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsEmitter is an autogenerated mock type for the MetricsEmitter type
type MockMetricsEmitter struct {
	mock.Mock
}

type MockMetricsEmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsEmitter) EXPECT() *MockMetricsEmitter_Expecter {
	return &MockMetricsEmitter_Expecter{mock: &_m.Mock}
}

// EmitCount provides a mock function for the type MockMetricsEmitter
func (_mock *MockMetricsEmitter) EmitCount(ctx context.Context, name string, count int) error {
	ret := _mock.Called(ctx, name, count)

	if len(ret) == 0 {
		panic("no return value specified for EmitCount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, name, count)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsEmitter_EmitCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitCount'
type MockMetricsEmitter_EmitCount_Call struct {
	*mock.Call
}

// EmitCount is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - count int
func (_e *MockMetricsEmitter_Expecter) EmitCount(ctx interface{}, name interface{}, count interface{}) *MockMetricsEmitter_EmitCount_Call {
	return &MockMetricsEmitter_EmitCount_Call{Call: _e.mock.On("EmitCount", ctx, name, count)}
}

func (_c *MockMetricsEmitter_EmitCount_Call) Run(run func(ctx context.Context, name string, count int)) *MockMetricsEmitter_EmitCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetricsEmitter_EmitCount_Call) Return(err error) *MockMetricsEmitter_EmitCount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsEmitter_EmitCount_Call) RunAndReturn(run func(ctx context.Context, name string, count int) error) *MockMetricsEmitter_EmitCount_Call {
	_c.Call.Return(run)
	return _c
}
