// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package journal

import (
	"context"
	"time"

	"github.com/jonsabados/saturdaysspinout/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// DeleteJournalEntry provides a mock function for the type MockStore
func (_mock *MockStore) DeleteJournalEntry(ctx context.Context, driverID int64, raceID int64) error {
	ret := _mock.Called(ctx, driverID, raceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJournalEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, driverID, raceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteJournalEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJournalEntry'
type MockStore_DeleteJournalEntry_Call struct {
	*mock.Call
}

// DeleteJournalEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - raceID int64
func (_e *MockStore_Expecter) DeleteJournalEntry(ctx interface{}, driverID interface{}, raceID interface{}) *MockStore_DeleteJournalEntry_Call {
	return &MockStore_DeleteJournalEntry_Call{Call: _e.mock.On("DeleteJournalEntry", ctx, driverID, raceID)}
}

func (_c *MockStore_DeleteJournalEntry_Call) Run(run func(ctx context.Context, driverID int64, raceID int64)) *MockStore_DeleteJournalEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_DeleteJournalEntry_Call) Return(err error) *MockStore_DeleteJournalEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteJournalEntry_Call) RunAndReturn(run func(ctx context.Context, driverID int64, raceID int64) error) *MockStore_DeleteJournalEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetDriverSession provides a mock function for the type MockStore
func (_mock *MockStore) GetDriverSession(ctx context.Context, driverID int64, startTime time.Time) (*store.DriverSession, error) {
	ret := _mock.Called(ctx, driverID, startTime)

	if len(ret) == 0 {
		panic("no return value specified for GetDriverSession")
	}

	var r0 *store.DriverSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time) (*store.DriverSession, error)); ok {
		return returnFunc(ctx, driverID, startTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time) *store.DriverSession); ok {
		r0 = returnFunc(ctx, driverID, startTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.DriverSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time) error); ok {
		r1 = returnFunc(ctx, driverID, startTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetDriverSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriverSession'
type MockStore_GetDriverSession_Call struct {
	*mock.Call
}

// GetDriverSession is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - startTime time.Time
func (_e *MockStore_Expecter) GetDriverSession(ctx interface{}, driverID interface{}, startTime interface{}) *MockStore_GetDriverSession_Call {
	return &MockStore_GetDriverSession_Call{Call: _e.mock.On("GetDriverSession", ctx, driverID, startTime)}
}

func (_c *MockStore_GetDriverSession_Call) Run(run func(ctx context.Context, driverID int64, startTime time.Time)) *MockStore_GetDriverSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetDriverSession_Call) Return(driverSession *store.DriverSession, err error) *MockStore_GetDriverSession_Call {
	_c.Call.Return(driverSession, err)
	return _c
}

func (_c *MockStore_GetDriverSession_Call) RunAndReturn(run func(ctx context.Context, driverID int64, startTime time.Time) (*store.DriverSession, error)) *MockStore_GetDriverSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetDriverSessions provides a mock function for the type MockStore
func (_mock *MockStore) GetDriverSessions(ctx context.Context, driverID int64, startTimes []time.Time) ([]store.DriverSession, error) {
	ret := _mock.Called(ctx, driverID, startTimes)

	if len(ret) == 0 {
		panic("no return value specified for GetDriverSessions")
	}

	var r0 []store.DriverSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []time.Time) ([]store.DriverSession, error)); ok {
		return returnFunc(ctx, driverID, startTimes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []time.Time) []store.DriverSession); ok {
		r0 = returnFunc(ctx, driverID, startTimes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.DriverSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, []time.Time) error); ok {
		r1 = returnFunc(ctx, driverID, startTimes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetDriverSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriverSessions'
type MockStore_GetDriverSessions_Call struct {
	*mock.Call
}

// GetDriverSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - startTimes []time.Time
func (_e *MockStore_Expecter) GetDriverSessions(ctx interface{}, driverID interface{}, startTimes interface{}) *MockStore_GetDriverSessions_Call {
	return &MockStore_GetDriverSessions_Call{Call: _e.mock.On("GetDriverSessions", ctx, driverID, startTimes)}
}

func (_c *MockStore_GetDriverSessions_Call) Run(run func(ctx context.Context, driverID int64, startTimes []time.Time)) *MockStore_GetDriverSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []time.Time
		if args[2] != nil {
			arg2 = args[2].([]time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetDriverSessions_Call) Return(driverSessions []store.DriverSession, err error) *MockStore_GetDriverSessions_Call {
	_c.Call.Return(driverSessions, err)
	return _c
}

func (_c *MockStore_GetDriverSessions_Call) RunAndReturn(run func(ctx context.Context, driverID int64, startTimes []time.Time) ([]store.DriverSession, error)) *MockStore_GetDriverSessions_Call {
	_c.Call.Return(run)
	return _c
}

// GetJournalEntries provides a mock function for the type MockStore
func (_mock *MockStore) GetJournalEntries(ctx context.Context, driverID int64, from time.Time, to time.Time) ([]store.RaceJournalEntry, error) {
	ret := _mock.Called(ctx, driverID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetJournalEntries")
	}

	var r0 []store.RaceJournalEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) ([]store.RaceJournalEntry, error)); ok {
		return returnFunc(ctx, driverID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) []store.RaceJournalEntry); ok {
		r0 = returnFunc(ctx, driverID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.RaceJournalEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, driverID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetJournalEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJournalEntries'
type MockStore_GetJournalEntries_Call struct {
	*mock.Call
}

// GetJournalEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - from time.Time
//   - to time.Time
func (_e *MockStore_Expecter) GetJournalEntries(ctx interface{}, driverID interface{}, from interface{}, to interface{}) *MockStore_GetJournalEntries_Call {
	return &MockStore_GetJournalEntries_Call{Call: _e.mock.On("GetJournalEntries", ctx, driverID, from, to)}
}

func (_c *MockStore_GetJournalEntries_Call) Run(run func(ctx context.Context, driverID int64, from time.Time, to time.Time)) *MockStore_GetJournalEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_GetJournalEntries_Call) Return(raceJournalEntrys []store.RaceJournalEntry, err error) *MockStore_GetJournalEntries_Call {
	_c.Call.Return(raceJournalEntrys, err)
	return _c
}

func (_c *MockStore_GetJournalEntries_Call) RunAndReturn(run func(ctx context.Context, driverID int64, from time.Time, to time.Time) ([]store.RaceJournalEntry, error)) *MockStore_GetJournalEntries_Call {
	_c.Call.Return(run)
	return _c
}

// GetJournalEntry provides a mock function for the type MockStore
func (_mock *MockStore) GetJournalEntry(ctx context.Context, driverID int64, raceID int64) (*store.RaceJournalEntry, error) {
	ret := _mock.Called(ctx, driverID, raceID)

	if len(ret) == 0 {
		panic("no return value specified for GetJournalEntry")
	}

	var r0 *store.RaceJournalEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*store.RaceJournalEntry, error)); ok {
		return returnFunc(ctx, driverID, raceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *store.RaceJournalEntry); ok {
		r0 = returnFunc(ctx, driverID, raceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.RaceJournalEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, driverID, raceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetJournalEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJournalEntry'
type MockStore_GetJournalEntry_Call struct {
	*mock.Call
}

// GetJournalEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - raceID int64
func (_e *MockStore_Expecter) GetJournalEntry(ctx interface{}, driverID interface{}, raceID interface{}) *MockStore_GetJournalEntry_Call {
	return &MockStore_GetJournalEntry_Call{Call: _e.mock.On("GetJournalEntry", ctx, driverID, raceID)}
}

func (_c *MockStore_GetJournalEntry_Call) Run(run func(ctx context.Context, driverID int64, raceID int64)) *MockStore_GetJournalEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetJournalEntry_Call) Return(raceJournalEntry *store.RaceJournalEntry, err error) *MockStore_GetJournalEntry_Call {
	_c.Call.Return(raceJournalEntry, err)
	return _c
}

func (_c *MockStore_GetJournalEntry_Call) RunAndReturn(run func(ctx context.Context, driverID int64, raceID int64) (*store.RaceJournalEntry, error)) *MockStore_GetJournalEntry_Call {
	_c.Call.Return(run)
	return _c
}

// SaveJournalEntry provides a mock function for the type MockStore
func (_mock *MockStore) SaveJournalEntry(ctx context.Context, entry store.RaceJournalEntry) error {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for SaveJournalEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.RaceJournalEntry) error); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SaveJournalEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveJournalEntry'
type MockStore_SaveJournalEntry_Call struct {
	*mock.Call
}

// SaveJournalEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entry store.RaceJournalEntry
func (_e *MockStore_Expecter) SaveJournalEntry(ctx interface{}, entry interface{}) *MockStore_SaveJournalEntry_Call {
	return &MockStore_SaveJournalEntry_Call{Call: _e.mock.On("SaveJournalEntry", ctx, entry)}
}

func (_c *MockStore_SaveJournalEntry_Call) Run(run func(ctx context.Context, entry store.RaceJournalEntry)) *MockStore_SaveJournalEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.RaceJournalEntry
		if args[1] != nil {
			arg1 = args[1].(store.RaceJournalEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SaveJournalEntry_Call) Return(err error) *MockStore_SaveJournalEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SaveJournalEntry_Call) RunAndReturn(run func(ctx context.Context, entry store.RaceJournalEntry) error) *MockStore_SaveJournalEntry_Call {
	_c.Call.Return(run)
	return _c
}
