// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package session

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/iracing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCombinedClient creates a new instance of MockCombinedClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCombinedClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCombinedClient {
	mock := &MockCombinedClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCombinedClient is an autogenerated mock type for the CombinedClient type
type MockCombinedClient struct {
	mock.Mock
}

type MockCombinedClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCombinedClient) EXPECT() *MockCombinedClient_Expecter {
	return &MockCombinedClient_Expecter{mock: &_m.Mock}
}

// GetLapData provides a mock function for the type MockCombinedClient
func (_mock *MockCombinedClient) GetLapData(ctx context.Context, accessToken string, subsessionID int64, simsessionNumber int, opts ...iracing.GetLapDataOption) (*iracing.LapDataResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, accessToken, subsessionID, simsessionNumber, opts)
	} else {
		tmpRet = _mock.Called(ctx, accessToken, subsessionID, simsessionNumber)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetLapData")
	}

	var r0 *iracing.LapDataResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int, ...iracing.GetLapDataOption) (*iracing.LapDataResponse, error)); ok {
		return returnFunc(ctx, accessToken, subsessionID, simsessionNumber, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int, ...iracing.GetLapDataOption) *iracing.LapDataResponse); ok {
		r0 = returnFunc(ctx, accessToken, subsessionID, simsessionNumber, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iracing.LapDataResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int, ...iracing.GetLapDataOption) error); ok {
		r1 = returnFunc(ctx, accessToken, subsessionID, simsessionNumber, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCombinedClient_GetLapData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLapData'
type MockCombinedClient_GetLapData_Call struct {
	*mock.Call
}

// GetLapData is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - subsessionID int64
//   - simsessionNumber int
//   - opts ...iracing.GetLapDataOption
func (_e *MockCombinedClient_Expecter) GetLapData(ctx interface{}, accessToken interface{}, subsessionID interface{}, simsessionNumber interface{}, opts ...interface{}) *MockCombinedClient_GetLapData_Call {
	return &MockCombinedClient_GetLapData_Call{Call: _e.mock.On("GetLapData",
		append([]interface{}{ctx, accessToken, subsessionID, simsessionNumber}, opts...)...)}
}

func (_c *MockCombinedClient_GetLapData_Call) Run(run func(ctx context.Context, accessToken string, subsessionID int64, simsessionNumber int, opts ...iracing.GetLapDataOption)) *MockCombinedClient_GetLapData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []iracing.GetLapDataOption
		var variadicArgs []iracing.GetLapDataOption
		if len(args) > 4 {
			variadicArgs = args[4].([]iracing.GetLapDataOption)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockCombinedClient_GetLapData_Call) Return(lapDataResponse *iracing.LapDataResponse, err error) *MockCombinedClient_GetLapData_Call {
	_c.Call.Return(lapDataResponse, err)
	return _c
}

func (_c *MockCombinedClient_GetLapData_Call) RunAndReturn(run func(ctx context.Context, accessToken string, subsessionID int64, simsessionNumber int, opts ...iracing.GetLapDataOption) (*iracing.LapDataResponse, error)) *MockCombinedClient_GetLapData_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionResults provides a mock function for the type MockCombinedClient
func (_mock *MockCombinedClient) GetSessionResults(ctx context.Context, accessToken string, subsessionID int64, opts ...iracing.GetSessionResultsOption) (*iracing.SessionResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, accessToken, subsessionID, opts)
	} else {
		tmpRet = _mock.Called(ctx, accessToken, subsessionID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSessionResults")
	}

	var r0 *iracing.SessionResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, ...iracing.GetSessionResultsOption) (*iracing.SessionResult, error)); ok {
		return returnFunc(ctx, accessToken, subsessionID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, ...iracing.GetSessionResultsOption) *iracing.SessionResult); ok {
		r0 = returnFunc(ctx, accessToken, subsessionID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iracing.SessionResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, ...iracing.GetSessionResultsOption) error); ok {
		r1 = returnFunc(ctx, accessToken, subsessionID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCombinedClient_GetSessionResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionResults'
type MockCombinedClient_GetSessionResults_Call struct {
	*mock.Call
}

// GetSessionResults is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - subsessionID int64
//   - opts ...iracing.GetSessionResultsOption
func (_e *MockCombinedClient_Expecter) GetSessionResults(ctx interface{}, accessToken interface{}, subsessionID interface{}, opts ...interface{}) *MockCombinedClient_GetSessionResults_Call {
	return &MockCombinedClient_GetSessionResults_Call{Call: _e.mock.On("GetSessionResults",
		append([]interface{}{ctx, accessToken, subsessionID}, opts...)...)}
}

func (_c *MockCombinedClient_GetSessionResults_Call) Run(run func(ctx context.Context, accessToken string, subsessionID int64, opts ...iracing.GetSessionResultsOption)) *MockCombinedClient_GetSessionResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 []iracing.GetSessionResultsOption
		var variadicArgs []iracing.GetSessionResultsOption
		if len(args) > 3 {
			variadicArgs = args[3].([]iracing.GetSessionResultsOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCombinedClient_GetSessionResults_Call) Return(sessionResult *iracing.SessionResult, err error) *MockCombinedClient_GetSessionResults_Call {
	_c.Call.Return(sessionResult, err)
	return _c
}

func (_c *MockCombinedClient_GetSessionResults_Call) RunAndReturn(run func(ctx context.Context, accessToken string, subsessionID int64, opts ...iracing.GetSessionResultsOption) (*iracing.SessionResult, error)) *MockCombinedClient_GetSessionResults_Call {
	_c.Call.Return(run)
	return _c
}
