// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package session

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/iracing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIRacingClient creates a new instance of MockIRacingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRacingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRacingClient {
	mock := &MockIRacingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRacingClient is an autogenerated mock type for the IRacingClient type
type MockIRacingClient struct {
	mock.Mock
}

type MockIRacingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRacingClient) EXPECT() *MockIRacingClient_Expecter {
	return &MockIRacingClient_Expecter{mock: &_m.Mock}
}

// GetSessionResults provides a mock function for the type MockIRacingClient
func (_mock *MockIRacingClient) GetSessionResults(ctx context.Context, accessToken string, subsessionID int64, opts ...iracing.GetSessionResultsOption) (*iracing.SessionResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, accessToken, subsessionID, opts)
	} else {
		tmpRet = _mock.Called(ctx, accessToken, subsessionID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSessionResults")
	}

	var r0 *iracing.SessionResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, ...iracing.GetSessionResultsOption) (*iracing.SessionResult, error)); ok {
		return returnFunc(ctx, accessToken, subsessionID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, ...iracing.GetSessionResultsOption) *iracing.SessionResult); ok {
		r0 = returnFunc(ctx, accessToken, subsessionID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iracing.SessionResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, ...iracing.GetSessionResultsOption) error); ok {
		r1 = returnFunc(ctx, accessToken, subsessionID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRacingClient_GetSessionResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionResults'
type MockIRacingClient_GetSessionResults_Call struct {
	*mock.Call
}

// GetSessionResults is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - subsessionID int64
//   - opts ...iracing.GetSessionResultsOption
func (_e *MockIRacingClient_Expecter) GetSessionResults(ctx interface{}, accessToken interface{}, subsessionID interface{}, opts ...interface{}) *MockIRacingClient_GetSessionResults_Call {
	return &MockIRacingClient_GetSessionResults_Call{Call: _e.mock.On("GetSessionResults",
		append([]interface{}{ctx, accessToken, subsessionID}, opts...)...)}
}

func (_c *MockIRacingClient_GetSessionResults_Call) Run(run func(ctx context.Context, accessToken string, subsessionID int64, opts ...iracing.GetSessionResultsOption)) *MockIRacingClient_GetSessionResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 []iracing.GetSessionResultsOption
		var variadicArgs []iracing.GetSessionResultsOption
		if len(args) > 3 {
			variadicArgs = args[3].([]iracing.GetSessionResultsOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockIRacingClient_GetSessionResults_Call) Return(sessionResult *iracing.SessionResult, err error) *MockIRacingClient_GetSessionResults_Call {
	_c.Call.Return(sessionResult, err)
	return _c
}

func (_c *MockIRacingClient_GetSessionResults_Call) RunAndReturn(run func(ctx context.Context, accessToken string, subsessionID int64, opts ...iracing.GetSessionResultsOption) (*iracing.SessionResult, error)) *MockIRacingClient_GetSessionResults_Call {
	_c.Call.Return(run)
	return _c
}
