// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ws

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionLookup creates a new instance of MockConnectionLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionLookup {
	mock := &MockConnectionLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionLookup is an autogenerated mock type for the ConnectionLookup type
type MockConnectionLookup struct {
	mock.Mock
}

type MockConnectionLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionLookup) EXPECT() *MockConnectionLookup_Expecter {
	return &MockConnectionLookup_Expecter{mock: &_m.Mock}
}

// GetConnectionsByDriver provides a mock function for the type MockConnectionLookup
func (_mock *MockConnectionLookup) GetConnectionsByDriver(ctx context.Context, driverID int64) ([]store.WebSocketConnection, error) {
	ret := _mock.Called(ctx, driverID)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionsByDriver")
	}

	var r0 []store.WebSocketConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]store.WebSocketConnection, error)); ok {
		return returnFunc(ctx, driverID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []store.WebSocketConnection); ok {
		r0 = returnFunc(ctx, driverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.WebSocketConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, driverID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionLookup_GetConnectionsByDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionsByDriver'
type MockConnectionLookup_GetConnectionsByDriver_Call struct {
	*mock.Call
}

// GetConnectionsByDriver is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
func (_e *MockConnectionLookup_Expecter) GetConnectionsByDriver(ctx interface{}, driverID interface{}) *MockConnectionLookup_GetConnectionsByDriver_Call {
	return &MockConnectionLookup_GetConnectionsByDriver_Call{Call: _e.mock.On("GetConnectionsByDriver", ctx, driverID)}
}

func (_c *MockConnectionLookup_GetConnectionsByDriver_Call) Run(run func(ctx context.Context, driverID int64)) *MockConnectionLookup_GetConnectionsByDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionLookup_GetConnectionsByDriver_Call) Return(webSocketConnections []store.WebSocketConnection, err error) *MockConnectionLookup_GetConnectionsByDriver_Call {
	_c.Call.Return(webSocketConnections, err)
	return _c
}

func (_c *MockConnectionLookup_GetConnectionsByDriver_Call) RunAndReturn(run func(ctx context.Context, driverID int64) ([]store.WebSocketConnection, error)) *MockConnectionLookup_GetConnectionsByDriver_Call {
	_c.Call.Return(run)
	return _c
}
