// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ws

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionDeleter creates a new instance of MockConnectionDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionDeleter {
	mock := &MockConnectionDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionDeleter is an autogenerated mock type for the ConnectionDeleter type
type MockConnectionDeleter struct {
	mock.Mock
}

type MockConnectionDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionDeleter) EXPECT() *MockConnectionDeleter_Expecter {
	return &MockConnectionDeleter_Expecter{mock: &_m.Mock}
}

// DeleteConnection provides a mock function for the type MockConnectionDeleter
func (_mock *MockConnectionDeleter) DeleteConnection(ctx context.Context, driverID int64, connectionID string) error {
	ret := _mock.Called(ctx, driverID, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, driverID, connectionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionDeleter_DeleteConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConnection'
type MockConnectionDeleter_DeleteConnection_Call struct {
	*mock.Call
}

// DeleteConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - driverID int64
//   - connectionID string
func (_e *MockConnectionDeleter_Expecter) DeleteConnection(ctx interface{}, driverID interface{}, connectionID interface{}) *MockConnectionDeleter_DeleteConnection_Call {
	return &MockConnectionDeleter_DeleteConnection_Call{Call: _e.mock.On("DeleteConnection", ctx, driverID, connectionID)}
}

func (_c *MockConnectionDeleter_DeleteConnection_Call) Run(run func(ctx context.Context, driverID int64, connectionID string)) *MockConnectionDeleter_DeleteConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectionDeleter_DeleteConnection_Call) Return(err error) *MockConnectionDeleter_DeleteConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionDeleter_DeleteConnection_Call) RunAndReturn(run func(ctx context.Context, driverID int64, connectionID string) error) *MockConnectionDeleter_DeleteConnection_Call {
	_c.Call.Return(run)
	return _c
}
