// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ws

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/apigatewaymanagementapi"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIGatewayManagementClient creates a new instance of MockAPIGatewayManagementClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIGatewayManagementClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIGatewayManagementClient {
	mock := &MockAPIGatewayManagementClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIGatewayManagementClient is an autogenerated mock type for the APIGatewayManagementClient type
type MockAPIGatewayManagementClient struct {
	mock.Mock
}

type MockAPIGatewayManagementClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIGatewayManagementClient) EXPECT() *MockAPIGatewayManagementClient_Expecter {
	return &MockAPIGatewayManagementClient_Expecter{mock: &_m.Mock}
}

// DeleteConnection provides a mock function for the type MockAPIGatewayManagementClient
func (_mock *MockAPIGatewayManagementClient) DeleteConnection(ctx context.Context, params *apigatewaymanagementapi.DeleteConnectionInput, optFns ...func(*apigatewaymanagementapi.Options)) (*apigatewaymanagementapi.DeleteConnectionOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnection")
	}

	var r0 *apigatewaymanagementapi.DeleteConnectionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewaymanagementapi.DeleteConnectionInput, ...func(*apigatewaymanagementapi.Options)) (*apigatewaymanagementapi.DeleteConnectionOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewaymanagementapi.DeleteConnectionInput, ...func(*apigatewaymanagementapi.Options)) *apigatewaymanagementapi.DeleteConnectionOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewaymanagementapi.DeleteConnectionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewaymanagementapi.DeleteConnectionInput, ...func(*apigatewaymanagementapi.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIGatewayManagementClient_DeleteConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConnection'
type MockAPIGatewayManagementClient_DeleteConnection_Call struct {
	*mock.Call
}

// DeleteConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - params *apigatewaymanagementapi.DeleteConnectionInput
//   - optFns ...func(*apigatewaymanagementapi.Options)
func (_e *MockAPIGatewayManagementClient_Expecter) DeleteConnection(ctx interface{}, params interface{}, optFns ...interface{}) *MockAPIGatewayManagementClient_DeleteConnection_Call {
	return &MockAPIGatewayManagementClient_DeleteConnection_Call{Call: _e.mock.On("DeleteConnection",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockAPIGatewayManagementClient_DeleteConnection_Call) Run(run func(ctx context.Context, params *apigatewaymanagementapi.DeleteConnectionInput, optFns ...func(*apigatewaymanagementapi.Options))) *MockAPIGatewayManagementClient_DeleteConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewaymanagementapi.DeleteConnectionInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewaymanagementapi.DeleteConnectionInput)
		}
		var arg2 []func(*apigatewaymanagementapi.Options)
		var variadicArgs []func(*apigatewaymanagementapi.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewaymanagementapi.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIGatewayManagementClient_DeleteConnection_Call) Return(deleteConnectionOutput *apigatewaymanagementapi.DeleteConnectionOutput, err error) *MockAPIGatewayManagementClient_DeleteConnection_Call {
	_c.Call.Return(deleteConnectionOutput, err)
	return _c
}

func (_c *MockAPIGatewayManagementClient_DeleteConnection_Call) RunAndReturn(run func(ctx context.Context, params *apigatewaymanagementapi.DeleteConnectionInput, optFns ...func(*apigatewaymanagementapi.Options)) (*apigatewaymanagementapi.DeleteConnectionOutput, error)) *MockAPIGatewayManagementClient_DeleteConnection_Call {
	_c.Call.Return(run)
	return _c
}

// PostToConnection provides a mock function for the type MockAPIGatewayManagementClient
func (_mock *MockAPIGatewayManagementClient) PostToConnection(ctx context.Context, params *apigatewaymanagementapi.PostToConnectionInput, optFns ...func(*apigatewaymanagementapi.Options)) (*apigatewaymanagementapi.PostToConnectionOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PostToConnection")
	}

	var r0 *apigatewaymanagementapi.PostToConnectionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewaymanagementapi.PostToConnectionInput, ...func(*apigatewaymanagementapi.Options)) (*apigatewaymanagementapi.PostToConnectionOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewaymanagementapi.PostToConnectionInput, ...func(*apigatewaymanagementapi.Options)) *apigatewaymanagementapi.PostToConnectionOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewaymanagementapi.PostToConnectionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewaymanagementapi.PostToConnectionInput, ...func(*apigatewaymanagementapi.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIGatewayManagementClient_PostToConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostToConnection'
type MockAPIGatewayManagementClient_PostToConnection_Call struct {
	*mock.Call
}

// PostToConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - params *apigatewaymanagementapi.PostToConnectionInput
//   - optFns ...func(*apigatewaymanagementapi.Options)
func (_e *MockAPIGatewayManagementClient_Expecter) PostToConnection(ctx interface{}, params interface{}, optFns ...interface{}) *MockAPIGatewayManagementClient_PostToConnection_Call {
	return &MockAPIGatewayManagementClient_PostToConnection_Call{Call: _e.mock.On("PostToConnection",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockAPIGatewayManagementClient_PostToConnection_Call) Run(run func(ctx context.Context, params *apigatewaymanagementapi.PostToConnectionInput, optFns ...func(*apigatewaymanagementapi.Options))) *MockAPIGatewayManagementClient_PostToConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewaymanagementapi.PostToConnectionInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewaymanagementapi.PostToConnectionInput)
		}
		var arg2 []func(*apigatewaymanagementapi.Options)
		var variadicArgs []func(*apigatewaymanagementapi.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewaymanagementapi.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIGatewayManagementClient_PostToConnection_Call) Return(postToConnectionOutput *apigatewaymanagementapi.PostToConnectionOutput, err error) *MockAPIGatewayManagementClient_PostToConnection_Call {
	_c.Call.Return(postToConnectionOutput, err)
	return _c
}

func (_c *MockAPIGatewayManagementClient_PostToConnection_Call) RunAndReturn(run func(ctx context.Context, params *apigatewaymanagementapi.PostToConnectionInput, optFns ...func(*apigatewaymanagementapi.Options)) (*apigatewaymanagementapi.PostToConnectionOutput, error)) *MockAPIGatewayManagementClient_PostToConnection_Call {
	_c.Call.Return(run)
	return _c
}
