// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ws

import (
	"context"

	"github.com/aws/aws-lambda-go/events"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRouteHandler creates a new instance of MockRouteHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouteHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouteHandler {
	mock := &MockRouteHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRouteHandler is an autogenerated mock type for the RouteHandler type
type MockRouteHandler struct {
	mock.Mock
}

type MockRouteHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRouteHandler) EXPECT() *MockRouteHandler_Expecter {
	return &MockRouteHandler_Expecter{mock: &_m.Mock}
}

// HandleRequest provides a mock function for the type MockRouteHandler
func (_mock *MockRouteHandler) HandleRequest(ctx context.Context, request events.APIGatewayWebsocketProxyRequest) (events.APIGatewayProxyResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for HandleRequest")
	}

	var r0 events.APIGatewayProxyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, events.APIGatewayWebsocketProxyRequest) (events.APIGatewayProxyResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, events.APIGatewayWebsocketProxyRequest) events.APIGatewayProxyResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(events.APIGatewayProxyResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, events.APIGatewayWebsocketProxyRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRouteHandler_HandleRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRequest'
type MockRouteHandler_HandleRequest_Call struct {
	*mock.Call
}

// HandleRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - request events.APIGatewayWebsocketProxyRequest
func (_e *MockRouteHandler_Expecter) HandleRequest(ctx interface{}, request interface{}) *MockRouteHandler_HandleRequest_Call {
	return &MockRouteHandler_HandleRequest_Call{Call: _e.mock.On("HandleRequest", ctx, request)}
}

func (_c *MockRouteHandler_HandleRequest_Call) Run(run func(ctx context.Context, request events.APIGatewayWebsocketProxyRequest)) *MockRouteHandler_HandleRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 events.APIGatewayWebsocketProxyRequest
		if args[1] != nil {
			arg1 = args[1].(events.APIGatewayWebsocketProxyRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRouteHandler_HandleRequest_Call) Return(aPIGatewayProxyResponse events.APIGatewayProxyResponse, err error) *MockRouteHandler_HandleRequest_Call {
	_c.Call.Return(aPIGatewayProxyResponse, err)
	return _c
}

func (_c *MockRouteHandler_HandleRequest_Call) RunAndReturn(run func(ctx context.Context, request events.APIGatewayWebsocketProxyRequest) (events.APIGatewayProxyResponse, error)) *MockRouteHandler_HandleRequest_Call {
	_c.Call.Return(run)
	return _c
}
