// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package series

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/iracing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIRacingClient creates a new instance of MockIRacingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRacingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRacingClient {
	mock := &MockIRacingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRacingClient is an autogenerated mock type for the IRacingClient type
type MockIRacingClient struct {
	mock.Mock
}

type MockIRacingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRacingClient) EXPECT() *MockIRacingClient_Expecter {
	return &MockIRacingClient_Expecter{mock: &_m.Mock}
}

// GetSeries provides a mock function for the type MockIRacingClient
func (_mock *MockIRacingClient) GetSeries(ctx context.Context, accessToken string) ([]iracing.SeriesInfo, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetSeries")
	}

	var r0 []iracing.SeriesInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]iracing.SeriesInfo, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []iracing.SeriesInfo); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iracing.SeriesInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRacingClient_GetSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeries'
type MockIRacingClient_GetSeries_Call struct {
	*mock.Call
}

// GetSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockIRacingClient_Expecter) GetSeries(ctx interface{}, accessToken interface{}) *MockIRacingClient_GetSeries_Call {
	return &MockIRacingClient_GetSeries_Call{Call: _e.mock.On("GetSeries", ctx, accessToken)}
}

func (_c *MockIRacingClient_GetSeries_Call) Run(run func(ctx context.Context, accessToken string)) *MockIRacingClient_GetSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRacingClient_GetSeries_Call) Return(seriesInfos []iracing.SeriesInfo, err error) *MockIRacingClient_GetSeries_Call {
	_c.Call.Return(seriesInfos, err)
	return _c
}

func (_c *MockIRacingClient_GetSeries_Call) RunAndReturn(run func(ctx context.Context, accessToken string) ([]iracing.SeriesInfo, error)) *MockIRacingClient_GetSeries_Call {
	_c.Call.Return(run)
	return _c
}
