// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	"github.com/jonsabados/saturdaysspinout/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenValidator creates a new instance of MockTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenValidator {
	mock := &MockTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenValidator is an autogenerated mock type for the TokenValidator type
type MockTokenValidator struct {
	mock.Mock
}

type MockTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenValidator) EXPECT() *MockTokenValidator_Expecter {
	return &MockTokenValidator_Expecter{mock: &_m.Mock}
}

// ValidateToken provides a mock function for the type MockTokenValidator
func (_mock *MockTokenValidator) ValidateToken(ctx context.Context, tokenString string) (*auth.SessionClaims, *auth.SensitiveClaims, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *auth.SessionClaims
	var r1 *auth.SensitiveClaims
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auth.SessionClaims, *auth.SensitiveClaims, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auth.SessionClaims); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.SessionClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *auth.SensitiveClaims); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*auth.SensitiveClaims)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, tokenString)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenValidator_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockTokenValidator_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockTokenValidator_Expecter) ValidateToken(ctx interface{}, tokenString interface{}) *MockTokenValidator_ValidateToken_Call {
	return &MockTokenValidator_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, tokenString)}
}

func (_c *MockTokenValidator_ValidateToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockTokenValidator_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenValidator_ValidateToken_Call) Return(sessionClaims *auth.SessionClaims, sensitiveClaims *auth.SensitiveClaims, err error) *MockTokenValidator_ValidateToken_Call {
	_c.Call.Return(sessionClaims, sensitiveClaims, err)
	return _c
}

func (_c *MockTokenValidator_ValidateToken_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (*auth.SessionClaims, *auth.SensitiveClaims, error)) *MockTokenValidator_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
