// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ingestion

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventDispatcher creates a new instance of MockEventDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventDispatcher {
	mock := &MockEventDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventDispatcher is an autogenerated mock type for the EventDispatcher type
type MockEventDispatcher struct {
	mock.Mock
}

type MockEventDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventDispatcher) EXPECT() *MockEventDispatcher_Expecter {
	return &MockEventDispatcher_Expecter{mock: &_m.Mock}
}

// PublishEvent provides a mock function for the type MockEventDispatcher
func (_mock *MockEventDispatcher) PublishEvent(ctx context.Context, event any) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventDispatcher_PublishEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishEvent'
type MockEventDispatcher_PublishEvent_Call struct {
	*mock.Call
}

// PublishEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event any
func (_e *MockEventDispatcher_Expecter) PublishEvent(ctx interface{}, event interface{}) *MockEventDispatcher_PublishEvent_Call {
	return &MockEventDispatcher_PublishEvent_Call{Call: _e.mock.On("PublishEvent", ctx, event)}
}

func (_c *MockEventDispatcher_PublishEvent_Call) Run(run func(ctx context.Context, event any)) *MockEventDispatcher_PublishEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventDispatcher_PublishEvent_Call) Return(err error) *MockEventDispatcher_PublishEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventDispatcher_PublishEvent_Call) RunAndReturn(run func(ctx context.Context, event any) error) *MockEventDispatcher_PublishEvent_Call {
	_c.Call.Return(run)
	return _c
}
